/* This file was generated by SableCC (http://www.sablecc.org/). */

package cmu.node;

import cmu.analysis.*;

@SuppressWarnings("nls")
public final class AAssinatura extends PAssinatura
{
    private TUmaFuncao _umaFuncao_;
    private TId _id_;
    private TEsqPar _esqPar_;
    private TQueArruma _queArruma_;
    private PTipo _tipo_;
    private TEmTrocaDe _emTrocaDe_;
    private PParametrosAssinatura _parametrosAssinatura_;
    private TDirPar _dirPar_;

    public AAssinatura()
    {
        // Constructor
    }

    public AAssinatura(
        @SuppressWarnings("hiding") TUmaFuncao _umaFuncao_,
        @SuppressWarnings("hiding") TId _id_,
        @SuppressWarnings("hiding") TEsqPar _esqPar_,
        @SuppressWarnings("hiding") TQueArruma _queArruma_,
        @SuppressWarnings("hiding") PTipo _tipo_,
        @SuppressWarnings("hiding") TEmTrocaDe _emTrocaDe_,
        @SuppressWarnings("hiding") PParametrosAssinatura _parametrosAssinatura_,
        @SuppressWarnings("hiding") TDirPar _dirPar_)
    {
        // Constructor
        setUmaFuncao(_umaFuncao_);

        setId(_id_);

        setEsqPar(_esqPar_);

        setQueArruma(_queArruma_);

        setTipo(_tipo_);

        setEmTrocaDe(_emTrocaDe_);

        setParametrosAssinatura(_parametrosAssinatura_);

        setDirPar(_dirPar_);

    }

    @Override
    public Object clone()
    {
        return new AAssinatura(
            cloneNode(this._umaFuncao_),
            cloneNode(this._id_),
            cloneNode(this._esqPar_),
            cloneNode(this._queArruma_),
            cloneNode(this._tipo_),
            cloneNode(this._emTrocaDe_),
            cloneNode(this._parametrosAssinatura_),
            cloneNode(this._dirPar_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAssinatura(this);
    }

    public TUmaFuncao getUmaFuncao()
    {
        return this._umaFuncao_;
    }

    public void setUmaFuncao(TUmaFuncao node)
    {
        if(this._umaFuncao_ != null)
        {
            this._umaFuncao_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._umaFuncao_ = node;
    }

    public TId getId()
    {
        return this._id_;
    }

    public void setId(TId node)
    {
        if(this._id_ != null)
        {
            this._id_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._id_ = node;
    }

    public TEsqPar getEsqPar()
    {
        return this._esqPar_;
    }

    public void setEsqPar(TEsqPar node)
    {
        if(this._esqPar_ != null)
        {
            this._esqPar_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._esqPar_ = node;
    }

    public TQueArruma getQueArruma()
    {
        return this._queArruma_;
    }

    public void setQueArruma(TQueArruma node)
    {
        if(this._queArruma_ != null)
        {
            this._queArruma_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._queArruma_ = node;
    }

    public PTipo getTipo()
    {
        return this._tipo_;
    }

    public void setTipo(PTipo node)
    {
        if(this._tipo_ != null)
        {
            this._tipo_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._tipo_ = node;
    }

    public TEmTrocaDe getEmTrocaDe()
    {
        return this._emTrocaDe_;
    }

    public void setEmTrocaDe(TEmTrocaDe node)
    {
        if(this._emTrocaDe_ != null)
        {
            this._emTrocaDe_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._emTrocaDe_ = node;
    }

    public PParametrosAssinatura getParametrosAssinatura()
    {
        return this._parametrosAssinatura_;
    }

    public void setParametrosAssinatura(PParametrosAssinatura node)
    {
        if(this._parametrosAssinatura_ != null)
        {
            this._parametrosAssinatura_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._parametrosAssinatura_ = node;
    }

    public TDirPar getDirPar()
    {
        return this._dirPar_;
    }

    public void setDirPar(TDirPar node)
    {
        if(this._dirPar_ != null)
        {
            this._dirPar_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._dirPar_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._umaFuncao_)
            + toString(this._id_)
            + toString(this._esqPar_)
            + toString(this._queArruma_)
            + toString(this._tipo_)
            + toString(this._emTrocaDe_)
            + toString(this._parametrosAssinatura_)
            + toString(this._dirPar_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._umaFuncao_ == child)
        {
            this._umaFuncao_ = null;
            return;
        }

        if(this._id_ == child)
        {
            this._id_ = null;
            return;
        }

        if(this._esqPar_ == child)
        {
            this._esqPar_ = null;
            return;
        }

        if(this._queArruma_ == child)
        {
            this._queArruma_ = null;
            return;
        }

        if(this._tipo_ == child)
        {
            this._tipo_ = null;
            return;
        }

        if(this._emTrocaDe_ == child)
        {
            this._emTrocaDe_ = null;
            return;
        }

        if(this._parametrosAssinatura_ == child)
        {
            this._parametrosAssinatura_ = null;
            return;
        }

        if(this._dirPar_ == child)
        {
            this._dirPar_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._umaFuncao_ == oldChild)
        {
            setUmaFuncao((TUmaFuncao) newChild);
            return;
        }

        if(this._id_ == oldChild)
        {
            setId((TId) newChild);
            return;
        }

        if(this._esqPar_ == oldChild)
        {
            setEsqPar((TEsqPar) newChild);
            return;
        }

        if(this._queArruma_ == oldChild)
        {
            setQueArruma((TQueArruma) newChild);
            return;
        }

        if(this._tipo_ == oldChild)
        {
            setTipo((PTipo) newChild);
            return;
        }

        if(this._emTrocaDe_ == oldChild)
        {
            setEmTrocaDe((TEmTrocaDe) newChild);
            return;
        }

        if(this._parametrosAssinatura_ == oldChild)
        {
            setParametrosAssinatura((PParametrosAssinatura) newChild);
            return;
        }

        if(this._dirPar_ == oldChild)
        {
            setDirPar((TDirPar) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
