/* This file was generated by SableCC (http://www.sablecc.org/). */

package cmu.node;

import cmu.analysis.*;

@SuppressWarnings("nls")
public final class ABaseTermoUnario extends PTermoUnario
{
    private PTermoBase _termoBase_;

    public ABaseTermoUnario()
    {
        // Constructor
    }

    public ABaseTermoUnario(
        @SuppressWarnings("hiding") PTermoBase _termoBase_)
    {
        // Constructor
        setTermoBase(_termoBase_);

    }

    @Override
    public Object clone()
    {
        return new ABaseTermoUnario(
            cloneNode(this._termoBase_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseABaseTermoUnario(this);
    }

    public PTermoBase getTermoBase()
    {
        return this._termoBase_;
    }

    public void setTermoBase(PTermoBase node)
    {
        if(this._termoBase_ != null)
        {
            this._termoBase_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._termoBase_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._termoBase_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._termoBase_ == child)
        {
            this._termoBase_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._termoBase_ == oldChild)
        {
            setTermoBase((PTermoBase) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
