/* This file was generated by SableCC (http://www.sablecc.org/). */

package cmu.node;

import cmu.analysis.*;

@SuppressWarnings("nls")
public final class AChamada extends PChamada
{
    private TId _id_;
    private TEsqCol _esqCol_;
    private PListaExp _listaExp_;
    private TDirCol _dirCol_;

    public AChamada()
    {
        // Constructor
    }

    public AChamada(
        @SuppressWarnings("hiding") TId _id_,
        @SuppressWarnings("hiding") TEsqCol _esqCol_,
        @SuppressWarnings("hiding") PListaExp _listaExp_,
        @SuppressWarnings("hiding") TDirCol _dirCol_)
    {
        // Constructor
        setId(_id_);

        setEsqCol(_esqCol_);

        setListaExp(_listaExp_);

        setDirCol(_dirCol_);

    }

    @Override
    public Object clone()
    {
        return new AChamada(
            cloneNode(this._id_),
            cloneNode(this._esqCol_),
            cloneNode(this._listaExp_),
            cloneNode(this._dirCol_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAChamada(this);
    }

    public TId getId()
    {
        return this._id_;
    }

    public void setId(TId node)
    {
        if(this._id_ != null)
        {
            this._id_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._id_ = node;
    }

    public TEsqCol getEsqCol()
    {
        return this._esqCol_;
    }

    public void setEsqCol(TEsqCol node)
    {
        if(this._esqCol_ != null)
        {
            this._esqCol_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._esqCol_ = node;
    }

    public PListaExp getListaExp()
    {
        return this._listaExp_;
    }

    public void setListaExp(PListaExp node)
    {
        if(this._listaExp_ != null)
        {
            this._listaExp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._listaExp_ = node;
    }

    public TDirCol getDirCol()
    {
        return this._dirCol_;
    }

    public void setDirCol(TDirCol node)
    {
        if(this._dirCol_ != null)
        {
            this._dirCol_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._dirCol_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._id_)
            + toString(this._esqCol_)
            + toString(this._listaExp_)
            + toString(this._dirCol_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._id_ == child)
        {
            this._id_ = null;
            return;
        }

        if(this._esqCol_ == child)
        {
            this._esqCol_ = null;
            return;
        }

        if(this._listaExp_ == child)
        {
            this._listaExp_ = null;
            return;
        }

        if(this._dirCol_ == child)
        {
            this._dirCol_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._id_ == oldChild)
        {
            setId((TId) newChild);
            return;
        }

        if(this._esqCol_ == oldChild)
        {
            setEsqCol((TEsqCol) newChild);
            return;
        }

        if(this._listaExp_ == oldChild)
        {
            setListaExp((PListaExp) newChild);
            return;
        }

        if(this._dirCol_ == oldChild)
        {
            setDirCol((TDirCol) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
