/* This file was generated by SableCC (http://www.sablecc.org/). */

package cmu.node;

import cmu.analysis.*;

@SuppressWarnings("nls")
public final class ACompletoPvaProd extends PPvaProd
{
    private TParaVoceArranjar _paraVoceArranjar_;

    public ACompletoPvaProd()
    {
        // Constructor
    }

    public ACompletoPvaProd(
        @SuppressWarnings("hiding") TParaVoceArranjar _paraVoceArranjar_)
    {
        // Constructor
        setParaVoceArranjar(_paraVoceArranjar_);

    }

    @Override
    public Object clone()
    {
        return new ACompletoPvaProd(
            cloneNode(this._paraVoceArranjar_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseACompletoPvaProd(this);
    }

    public TParaVoceArranjar getParaVoceArranjar()
    {
        return this._paraVoceArranjar_;
    }

    public void setParaVoceArranjar(TParaVoceArranjar node)
    {
        if(this._paraVoceArranjar_ != null)
        {
            this._paraVoceArranjar_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._paraVoceArranjar_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._paraVoceArranjar_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._paraVoceArranjar_ == child)
        {
            this._paraVoceArranjar_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._paraVoceArranjar_ == oldChild)
        {
            setParaVoceArranjar((TParaVoceArranjar) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
