/* This file was generated by SableCC (http://www.sablecc.org/). */

package cmu.node;

import cmu.analysis.*;

@SuppressWarnings("nls")
public final class ACondicaoTernariaExpRetorno extends PExpRetorno
{
    private PCondicaoTernaria _condicaoTernaria_;

    public ACondicaoTernariaExpRetorno()
    {
        // Constructor
    }

    public ACondicaoTernariaExpRetorno(
        @SuppressWarnings("hiding") PCondicaoTernaria _condicaoTernaria_)
    {
        // Constructor
        setCondicaoTernaria(_condicaoTernaria_);

    }

    @Override
    public Object clone()
    {
        return new ACondicaoTernariaExpRetorno(
            cloneNode(this._condicaoTernaria_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseACondicaoTernariaExpRetorno(this);
    }

    public PCondicaoTernaria getCondicaoTernaria()
    {
        return this._condicaoTernaria_;
    }

    public void setCondicaoTernaria(PCondicaoTernaria node)
    {
        if(this._condicaoTernaria_ != null)
        {
            this._condicaoTernaria_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._condicaoTernaria_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._condicaoTernaria_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._condicaoTernaria_ == child)
        {
            this._condicaoTernaria_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._condicaoTernaria_ == oldChild)
        {
            setCondicaoTernaria((PCondicaoTernaria) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
