/* This file was generated by SableCC (http://www.sablecc.org/). */

package cmu.node;

import cmu.analysis.*;

@SuppressWarnings("nls")
public final class ADecFuncao extends PDecFuncao
{
    private TMarcadorInicio _marcador_;
    private TAFuncao _aFuncao_;
    private TId _id_;
    private TArruma _arruma_;
    private PTipo _tipo_;
    private TPonto _p1_;
    private TSeCond _seCond_;
    private PParametros _parametros_;
    private TVirgula _v1_;
    private TParaVoceArranjar _paraVoceArranjar_;
    private TVirgula _v2_;
    private TOValorDe _oValorDe_;
    private PExpRetorno _expRetorno_;
    private PSecaoConstantes _secaoConstantes_;
    private TElaIraTeRetornar _elaIraTeRetornar_;
    private TPonto _p2_;

    public ADecFuncao()
    {
        // Constructor
    }

    public ADecFuncao(
        @SuppressWarnings("hiding") TMarcadorInicio _marcador_,
        @SuppressWarnings("hiding") TAFuncao _aFuncao_,
        @SuppressWarnings("hiding") TId _id_,
        @SuppressWarnings("hiding") TArruma _arruma_,
        @SuppressWarnings("hiding") PTipo _tipo_,
        @SuppressWarnings("hiding") TPonto _p1_,
        @SuppressWarnings("hiding") TSeCond _seCond_,
        @SuppressWarnings("hiding") PParametros _parametros_,
        @SuppressWarnings("hiding") TVirgula _v1_,
        @SuppressWarnings("hiding") TParaVoceArranjar _paraVoceArranjar_,
        @SuppressWarnings("hiding") TVirgula _v2_,
        @SuppressWarnings("hiding") TOValorDe _oValorDe_,
        @SuppressWarnings("hiding") PExpRetorno _expRetorno_,
        @SuppressWarnings("hiding") PSecaoConstantes _secaoConstantes_,
        @SuppressWarnings("hiding") TElaIraTeRetornar _elaIraTeRetornar_,
        @SuppressWarnings("hiding") TPonto _p2_)
    {
        // Constructor
        setMarcador(_marcador_);

        setAFuncao(_aFuncao_);

        setId(_id_);

        setArruma(_arruma_);

        setTipo(_tipo_);

        setP1(_p1_);

        setSeCond(_seCond_);

        setParametros(_parametros_);

        setV1(_v1_);

        setParaVoceArranjar(_paraVoceArranjar_);

        setV2(_v2_);

        setOValorDe(_oValorDe_);

        setExpRetorno(_expRetorno_);

        setSecaoConstantes(_secaoConstantes_);

        setElaIraTeRetornar(_elaIraTeRetornar_);

        setP2(_p2_);

    }

    @Override
    public Object clone()
    {
        return new ADecFuncao(
            cloneNode(this._marcador_),
            cloneNode(this._aFuncao_),
            cloneNode(this._id_),
            cloneNode(this._arruma_),
            cloneNode(this._tipo_),
            cloneNode(this._p1_),
            cloneNode(this._seCond_),
            cloneNode(this._parametros_),
            cloneNode(this._v1_),
            cloneNode(this._paraVoceArranjar_),
            cloneNode(this._v2_),
            cloneNode(this._oValorDe_),
            cloneNode(this._expRetorno_),
            cloneNode(this._secaoConstantes_),
            cloneNode(this._elaIraTeRetornar_),
            cloneNode(this._p2_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseADecFuncao(this);
    }

    public TMarcadorInicio getMarcador()
    {
        return this._marcador_;
    }

    public void setMarcador(TMarcadorInicio node)
    {
        if(this._marcador_ != null)
        {
            this._marcador_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._marcador_ = node;
    }

    public TAFuncao getAFuncao()
    {
        return this._aFuncao_;
    }

    public void setAFuncao(TAFuncao node)
    {
        if(this._aFuncao_ != null)
        {
            this._aFuncao_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._aFuncao_ = node;
    }

    public TId getId()
    {
        return this._id_;
    }

    public void setId(TId node)
    {
        if(this._id_ != null)
        {
            this._id_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._id_ = node;
    }

    public TArruma getArruma()
    {
        return this._arruma_;
    }

    public void setArruma(TArruma node)
    {
        if(this._arruma_ != null)
        {
            this._arruma_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._arruma_ = node;
    }

    public PTipo getTipo()
    {
        return this._tipo_;
    }

    public void setTipo(PTipo node)
    {
        if(this._tipo_ != null)
        {
            this._tipo_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._tipo_ = node;
    }

    public TPonto getP1()
    {
        return this._p1_;
    }

    public void setP1(TPonto node)
    {
        if(this._p1_ != null)
        {
            this._p1_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._p1_ = node;
    }

    public TSeCond getSeCond()
    {
        return this._seCond_;
    }

    public void setSeCond(TSeCond node)
    {
        if(this._seCond_ != null)
        {
            this._seCond_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._seCond_ = node;
    }

    public PParametros getParametros()
    {
        return this._parametros_;
    }

    public void setParametros(PParametros node)
    {
        if(this._parametros_ != null)
        {
            this._parametros_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._parametros_ = node;
    }

    public TVirgula getV1()
    {
        return this._v1_;
    }

    public void setV1(TVirgula node)
    {
        if(this._v1_ != null)
        {
            this._v1_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._v1_ = node;
    }

    public TParaVoceArranjar getParaVoceArranjar()
    {
        return this._paraVoceArranjar_;
    }

    public void setParaVoceArranjar(TParaVoceArranjar node)
    {
        if(this._paraVoceArranjar_ != null)
        {
            this._paraVoceArranjar_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._paraVoceArranjar_ = node;
    }

    public TVirgula getV2()
    {
        return this._v2_;
    }

    public void setV2(TVirgula node)
    {
        if(this._v2_ != null)
        {
            this._v2_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._v2_ = node;
    }

    public TOValorDe getOValorDe()
    {
        return this._oValorDe_;
    }

    public void setOValorDe(TOValorDe node)
    {
        if(this._oValorDe_ != null)
        {
            this._oValorDe_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._oValorDe_ = node;
    }

    public PExpRetorno getExpRetorno()
    {
        return this._expRetorno_;
    }

    public void setExpRetorno(PExpRetorno node)
    {
        if(this._expRetorno_ != null)
        {
            this._expRetorno_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expRetorno_ = node;
    }

    public PSecaoConstantes getSecaoConstantes()
    {
        return this._secaoConstantes_;
    }

    public void setSecaoConstantes(PSecaoConstantes node)
    {
        if(this._secaoConstantes_ != null)
        {
            this._secaoConstantes_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._secaoConstantes_ = node;
    }

    public TElaIraTeRetornar getElaIraTeRetornar()
    {
        return this._elaIraTeRetornar_;
    }

    public void setElaIraTeRetornar(TElaIraTeRetornar node)
    {
        if(this._elaIraTeRetornar_ != null)
        {
            this._elaIraTeRetornar_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._elaIraTeRetornar_ = node;
    }

    public TPonto getP2()
    {
        return this._p2_;
    }

    public void setP2(TPonto node)
    {
        if(this._p2_ != null)
        {
            this._p2_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._p2_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._marcador_)
            + toString(this._aFuncao_)
            + toString(this._id_)
            + toString(this._arruma_)
            + toString(this._tipo_)
            + toString(this._p1_)
            + toString(this._seCond_)
            + toString(this._parametros_)
            + toString(this._v1_)
            + toString(this._paraVoceArranjar_)
            + toString(this._v2_)
            + toString(this._oValorDe_)
            + toString(this._expRetorno_)
            + toString(this._secaoConstantes_)
            + toString(this._elaIraTeRetornar_)
            + toString(this._p2_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._marcador_ == child)
        {
            this._marcador_ = null;
            return;
        }

        if(this._aFuncao_ == child)
        {
            this._aFuncao_ = null;
            return;
        }

        if(this._id_ == child)
        {
            this._id_ = null;
            return;
        }

        if(this._arruma_ == child)
        {
            this._arruma_ = null;
            return;
        }

        if(this._tipo_ == child)
        {
            this._tipo_ = null;
            return;
        }

        if(this._p1_ == child)
        {
            this._p1_ = null;
            return;
        }

        if(this._seCond_ == child)
        {
            this._seCond_ = null;
            return;
        }

        if(this._parametros_ == child)
        {
            this._parametros_ = null;
            return;
        }

        if(this._v1_ == child)
        {
            this._v1_ = null;
            return;
        }

        if(this._paraVoceArranjar_ == child)
        {
            this._paraVoceArranjar_ = null;
            return;
        }

        if(this._v2_ == child)
        {
            this._v2_ = null;
            return;
        }

        if(this._oValorDe_ == child)
        {
            this._oValorDe_ = null;
            return;
        }

        if(this._expRetorno_ == child)
        {
            this._expRetorno_ = null;
            return;
        }

        if(this._secaoConstantes_ == child)
        {
            this._secaoConstantes_ = null;
            return;
        }

        if(this._elaIraTeRetornar_ == child)
        {
            this._elaIraTeRetornar_ = null;
            return;
        }

        if(this._p2_ == child)
        {
            this._p2_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._marcador_ == oldChild)
        {
            setMarcador((TMarcadorInicio) newChild);
            return;
        }

        if(this._aFuncao_ == oldChild)
        {
            setAFuncao((TAFuncao) newChild);
            return;
        }

        if(this._id_ == oldChild)
        {
            setId((TId) newChild);
            return;
        }

        if(this._arruma_ == oldChild)
        {
            setArruma((TArruma) newChild);
            return;
        }

        if(this._tipo_ == oldChild)
        {
            setTipo((PTipo) newChild);
            return;
        }

        if(this._p1_ == oldChild)
        {
            setP1((TPonto) newChild);
            return;
        }

        if(this._seCond_ == oldChild)
        {
            setSeCond((TSeCond) newChild);
            return;
        }

        if(this._parametros_ == oldChild)
        {
            setParametros((PParametros) newChild);
            return;
        }

        if(this._v1_ == oldChild)
        {
            setV1((TVirgula) newChild);
            return;
        }

        if(this._paraVoceArranjar_ == oldChild)
        {
            setParaVoceArranjar((TParaVoceArranjar) newChild);
            return;
        }

        if(this._v2_ == oldChild)
        {
            setV2((TVirgula) newChild);
            return;
        }

        if(this._oValorDe_ == oldChild)
        {
            setOValorDe((TOValorDe) newChild);
            return;
        }

        if(this._expRetorno_ == oldChild)
        {
            setExpRetorno((PExpRetorno) newChild);
            return;
        }

        if(this._secaoConstantes_ == oldChild)
        {
            setSecaoConstantes((PSecaoConstantes) newChild);
            return;
        }

        if(this._elaIraTeRetornar_ == oldChild)
        {
            setElaIraTeRetornar((TElaIraTeRetornar) newChild);
            return;
        }

        if(this._p2_ == oldChild)
        {
            setP2((TPonto) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
