/* This file was generated by SableCC (http://www.sablecc.org/). */

package cmu.node;

import cmu.analysis.*;

@SuppressWarnings("nls")
public final class ADivTermoFator extends PTermoFator
{
    private PTermoFator _termoFator_;
    private TDiv _div_;
    private PTermoUnario _termoUnario_;

    public ADivTermoFator()
    {
        // Constructor
    }

    public ADivTermoFator(
        @SuppressWarnings("hiding") PTermoFator _termoFator_,
        @SuppressWarnings("hiding") TDiv _div_,
        @SuppressWarnings("hiding") PTermoUnario _termoUnario_)
    {
        // Constructor
        setTermoFator(_termoFator_);

        setDiv(_div_);

        setTermoUnario(_termoUnario_);

    }

    @Override
    public Object clone()
    {
        return new ADivTermoFator(
            cloneNode(this._termoFator_),
            cloneNode(this._div_),
            cloneNode(this._termoUnario_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseADivTermoFator(this);
    }

    public PTermoFator getTermoFator()
    {
        return this._termoFator_;
    }

    public void setTermoFator(PTermoFator node)
    {
        if(this._termoFator_ != null)
        {
            this._termoFator_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._termoFator_ = node;
    }

    public TDiv getDiv()
    {
        return this._div_;
    }

    public void setDiv(TDiv node)
    {
        if(this._div_ != null)
        {
            this._div_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._div_ = node;
    }

    public PTermoUnario getTermoUnario()
    {
        return this._termoUnario_;
    }

    public void setTermoUnario(PTermoUnario node)
    {
        if(this._termoUnario_ != null)
        {
            this._termoUnario_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._termoUnario_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._termoFator_)
            + toString(this._div_)
            + toString(this._termoUnario_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._termoFator_ == child)
        {
            this._termoFator_ = null;
            return;
        }

        if(this._div_ == child)
        {
            this._div_ = null;
            return;
        }

        if(this._termoUnario_ == child)
        {
            this._termoUnario_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._termoFator_ == oldChild)
        {
            setTermoFator((PTermoFator) newChild);
            return;
        }

        if(this._div_ == oldChild)
        {
            setDiv((TDiv) newChild);
            return;
        }

        if(this._termoUnario_ == oldChild)
        {
            setTermoUnario((PTermoUnario) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
