/* This file was generated by SableCC (http://www.sablecc.org/). */

package cmu.node;

import cmu.analysis.*;

@SuppressWarnings("nls")
public final class ADuploParametroMultiplo extends PParametroMultiplo
{
    private PParamGeral _p1_;
    private TEConn _eConn_;
    private PParamGeral _p2_;

    public ADuploParametroMultiplo()
    {
        // Constructor
    }

    public ADuploParametroMultiplo(
        @SuppressWarnings("hiding") PParamGeral _p1_,
        @SuppressWarnings("hiding") TEConn _eConn_,
        @SuppressWarnings("hiding") PParamGeral _p2_)
    {
        // Constructor
        setP1(_p1_);

        setEConn(_eConn_);

        setP2(_p2_);

    }

    @Override
    public Object clone()
    {
        return new ADuploParametroMultiplo(
            cloneNode(this._p1_),
            cloneNode(this._eConn_),
            cloneNode(this._p2_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseADuploParametroMultiplo(this);
    }

    public PParamGeral getP1()
    {
        return this._p1_;
    }

    public void setP1(PParamGeral node)
    {
        if(this._p1_ != null)
        {
            this._p1_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._p1_ = node;
    }

    public TEConn getEConn()
    {
        return this._eConn_;
    }

    public void setEConn(TEConn node)
    {
        if(this._eConn_ != null)
        {
            this._eConn_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._eConn_ = node;
    }

    public PParamGeral getP2()
    {
        return this._p2_;
    }

    public void setP2(PParamGeral node)
    {
        if(this._p2_ != null)
        {
            this._p2_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._p2_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._p1_)
            + toString(this._eConn_)
            + toString(this._p2_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._p1_ == child)
        {
            this._p1_ = null;
            return;
        }

        if(this._eConn_ == child)
        {
            this._eConn_ = null;
            return;
        }

        if(this._p2_ == child)
        {
            this._p2_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._p1_ == oldChild)
        {
            setP1((PParamGeral) newChild);
            return;
        }

        if(this._eConn_ == oldChild)
        {
            setEConn((TEConn) newChild);
            return;
        }

        if(this._p2_ == oldChild)
        {
            setP2((PParamGeral) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
