/* This file was generated by SableCC (http://www.sablecc.org/). */

package cmu.node;

import cmu.analysis.*;

@SuppressWarnings("nls")
public final class AEExpConjuncao extends PExpConjuncao
{
    private PExpConjuncao _expConjuncao_;
    private TEConn _eConn_;
    private PExpRelacional _expRelacional_;

    public AEExpConjuncao()
    {
        // Constructor
    }

    public AEExpConjuncao(
        @SuppressWarnings("hiding") PExpConjuncao _expConjuncao_,
        @SuppressWarnings("hiding") TEConn _eConn_,
        @SuppressWarnings("hiding") PExpRelacional _expRelacional_)
    {
        // Constructor
        setExpConjuncao(_expConjuncao_);

        setEConn(_eConn_);

        setExpRelacional(_expRelacional_);

    }

    @Override
    public Object clone()
    {
        return new AEExpConjuncao(
            cloneNode(this._expConjuncao_),
            cloneNode(this._eConn_),
            cloneNode(this._expRelacional_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAEExpConjuncao(this);
    }

    public PExpConjuncao getExpConjuncao()
    {
        return this._expConjuncao_;
    }

    public void setExpConjuncao(PExpConjuncao node)
    {
        if(this._expConjuncao_ != null)
        {
            this._expConjuncao_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expConjuncao_ = node;
    }

    public TEConn getEConn()
    {
        return this._eConn_;
    }

    public void setEConn(TEConn node)
    {
        if(this._eConn_ != null)
        {
            this._eConn_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._eConn_ = node;
    }

    public PExpRelacional getExpRelacional()
    {
        return this._expRelacional_;
    }

    public void setExpRelacional(PExpRelacional node)
    {
        if(this._expRelacional_ != null)
        {
            this._expRelacional_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expRelacional_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._expConjuncao_)
            + toString(this._eConn_)
            + toString(this._expRelacional_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._expConjuncao_ == child)
        {
            this._expConjuncao_ = null;
            return;
        }

        if(this._eConn_ == child)
        {
            this._eConn_ = null;
            return;
        }

        if(this._expRelacional_ == child)
        {
            this._expRelacional_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._expConjuncao_ == oldChild)
        {
            setExpConjuncao((PExpConjuncao) newChild);
            return;
        }

        if(this._eConn_ == oldChild)
        {
            setEConn((TEConn) newChild);
            return;
        }

        if(this._expRelacional_ == oldChild)
        {
            setExpRelacional((PExpRelacional) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
