/* This file was generated by SableCC (http://www.sablecc.org/). */

package cmu.node;

import cmu.analysis.*;

@SuppressWarnings("nls")
public final class AElementosListaExp extends PListaExp
{
    private PListaExpElems _listaExpElems_;

    public AElementosListaExp()
    {
        // Constructor
    }

    public AElementosListaExp(
        @SuppressWarnings("hiding") PListaExpElems _listaExpElems_)
    {
        // Constructor
        setListaExpElems(_listaExpElems_);

    }

    @Override
    public Object clone()
    {
        return new AElementosListaExp(
            cloneNode(this._listaExpElems_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAElementosListaExp(this);
    }

    public PListaExpElems getListaExpElems()
    {
        return this._listaExpElems_;
    }

    public void setListaExpElems(PListaExpElems node)
    {
        if(this._listaExpElems_ != null)
        {
            this._listaExpElems_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._listaExpElems_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._listaExpElems_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._listaExpElems_ == child)
        {
            this._listaExpElems_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._listaExpElems_ == oldChild)
        {
            setListaExpElems((PListaExpElems) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
