/* This file was generated by SableCC (http://www.sablecc.org/). */

package cmu.node;

import cmu.analysis.*;

@SuppressWarnings("nls")
public final class AETermoLogico extends PTermoLogico
{
    private PTermoLogico _termoLogico_;
    private TEConn _eConn_;
    private PTermoRelacional _termoRelacional_;

    public AETermoLogico()
    {
        // Constructor
    }

    public AETermoLogico(
        @SuppressWarnings("hiding") PTermoLogico _termoLogico_,
        @SuppressWarnings("hiding") TEConn _eConn_,
        @SuppressWarnings("hiding") PTermoRelacional _termoRelacional_)
    {
        // Constructor
        setTermoLogico(_termoLogico_);

        setEConn(_eConn_);

        setTermoRelacional(_termoRelacional_);

    }

    @Override
    public Object clone()
    {
        return new AETermoLogico(
            cloneNode(this._termoLogico_),
            cloneNode(this._eConn_),
            cloneNode(this._termoRelacional_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAETermoLogico(this);
    }

    public PTermoLogico getTermoLogico()
    {
        return this._termoLogico_;
    }

    public void setTermoLogico(PTermoLogico node)
    {
        if(this._termoLogico_ != null)
        {
            this._termoLogico_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._termoLogico_ = node;
    }

    public TEConn getEConn()
    {
        return this._eConn_;
    }

    public void setEConn(TEConn node)
    {
        if(this._eConn_ != null)
        {
            this._eConn_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._eConn_ = node;
    }

    public PTermoRelacional getTermoRelacional()
    {
        return this._termoRelacional_;
    }

    public void setTermoRelacional(PTermoRelacional node)
    {
        if(this._termoRelacional_ != null)
        {
            this._termoRelacional_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._termoRelacional_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._termoLogico_)
            + toString(this._eConn_)
            + toString(this._termoRelacional_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._termoLogico_ == child)
        {
            this._termoLogico_ = null;
            return;
        }

        if(this._eConn_ == child)
        {
            this._eConn_ = null;
            return;
        }

        if(this._termoRelacional_ == child)
        {
            this._termoRelacional_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._termoLogico_ == oldChild)
        {
            setTermoLogico((PTermoLogico) newChild);
            return;
        }

        if(this._eConn_ == oldChild)
        {
            setEConn((TEConn) newChild);
            return;
        }

        if(this._termoRelacional_ == oldChild)
        {
            setTermoRelacional((PTermoRelacional) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
