/* This file was generated by SableCC (http://www.sablecc.org/). */

package cmu.node;

import cmu.analysis.*;

@SuppressWarnings("nls")
public final class AFatorExpAritmetica extends PExpAritmetica
{
    private PExpFator _expFator_;

    public AFatorExpAritmetica()
    {
        // Constructor
    }

    public AFatorExpAritmetica(
        @SuppressWarnings("hiding") PExpFator _expFator_)
    {
        // Constructor
        setExpFator(_expFator_);

    }

    @Override
    public Object clone()
    {
        return new AFatorExpAritmetica(
            cloneNode(this._expFator_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAFatorExpAritmetica(this);
    }

    public PExpFator getExpFator()
    {
        return this._expFator_;
    }

    public void setExpFator(PExpFator node)
    {
        if(this._expFator_ != null)
        {
            this._expFator_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expFator_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._expFator_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._expFator_ == child)
        {
            this._expFator_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._expFator_ == oldChild)
        {
            setExpFator((PExpFator) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
