/* This file was generated by SableCC (http://www.sablecc.org/). */

package cmu.node;

import cmu.analysis.*;

@SuppressWarnings("nls")
public final class AFatorTermoAritmetico extends PTermoAritmetico
{
    private PTermoFator _termoFator_;

    public AFatorTermoAritmetico()
    {
        // Constructor
    }

    public AFatorTermoAritmetico(
        @SuppressWarnings("hiding") PTermoFator _termoFator_)
    {
        // Constructor
        setTermoFator(_termoFator_);

    }

    @Override
    public Object clone()
    {
        return new AFatorTermoAritmetico(
            cloneNode(this._termoFator_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAFatorTermoAritmetico(this);
    }

    public PTermoFator getTermoFator()
    {
        return this._termoFator_;
    }

    public void setTermoFator(PTermoFator node)
    {
        if(this._termoFator_ != null)
        {
            this._termoFator_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._termoFator_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._termoFator_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._termoFator_ == child)
        {
            this._termoFator_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._termoFator_ == oldChild)
        {
            setTermoFator((PTermoFator) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
