/* This file was generated by SableCC (http://www.sablecc.org/). */

package cmu.node;

import cmu.analysis.*;

@SuppressWarnings("nls")
public final class AIgualTermoRelacional extends PTermoRelacional
{
    private PTermoRelacional _termoRelacional_;
    private TIgual _igual_;
    private PTermoAritmetico _termoAritmetico_;

    public AIgualTermoRelacional()
    {
        // Constructor
    }

    public AIgualTermoRelacional(
        @SuppressWarnings("hiding") PTermoRelacional _termoRelacional_,
        @SuppressWarnings("hiding") TIgual _igual_,
        @SuppressWarnings("hiding") PTermoAritmetico _termoAritmetico_)
    {
        // Constructor
        setTermoRelacional(_termoRelacional_);

        setIgual(_igual_);

        setTermoAritmetico(_termoAritmetico_);

    }

    @Override
    public Object clone()
    {
        return new AIgualTermoRelacional(
            cloneNode(this._termoRelacional_),
            cloneNode(this._igual_),
            cloneNode(this._termoAritmetico_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAIgualTermoRelacional(this);
    }

    public PTermoRelacional getTermoRelacional()
    {
        return this._termoRelacional_;
    }

    public void setTermoRelacional(PTermoRelacional node)
    {
        if(this._termoRelacional_ != null)
        {
            this._termoRelacional_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._termoRelacional_ = node;
    }

    public TIgual getIgual()
    {
        return this._igual_;
    }

    public void setIgual(TIgual node)
    {
        if(this._igual_ != null)
        {
            this._igual_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._igual_ = node;
    }

    public PTermoAritmetico getTermoAritmetico()
    {
        return this._termoAritmetico_;
    }

    public void setTermoAritmetico(PTermoAritmetico node)
    {
        if(this._termoAritmetico_ != null)
        {
            this._termoAritmetico_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._termoAritmetico_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._termoRelacional_)
            + toString(this._igual_)
            + toString(this._termoAritmetico_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._termoRelacional_ == child)
        {
            this._termoRelacional_ = null;
            return;
        }

        if(this._igual_ == child)
        {
            this._igual_ = null;
            return;
        }

        if(this._termoAritmetico_ == child)
        {
            this._termoAritmetico_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._termoRelacional_ == oldChild)
        {
            setTermoRelacional((PTermoRelacional) newChild);
            return;
        }

        if(this._igual_ == oldChild)
        {
            setIgual((TIgual) newChild);
            return;
        }

        if(this._termoAritmetico_ == oldChild)
        {
            setTermoAritmetico((PTermoAritmetico) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
