/* This file was generated by SableCC (http://www.sablecc.org/). */

package cmu.node;

import cmu.analysis.*;

@SuppressWarnings("nls")
public final class AListaParametros extends PParametros
{
    private PParametroMultiplo _parametroMultiplo_;

    public AListaParametros()
    {
        // Constructor
    }

    public AListaParametros(
        @SuppressWarnings("hiding") PParametroMultiplo _parametroMultiplo_)
    {
        // Constructor
        setParametroMultiplo(_parametroMultiplo_);

    }

    @Override
    public Object clone()
    {
        return new AListaParametros(
            cloneNode(this._parametroMultiplo_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAListaParametros(this);
    }

    public PParametroMultiplo getParametroMultiplo()
    {
        return this._parametroMultiplo_;
    }

    public void setParametroMultiplo(PParametroMultiplo node)
    {
        if(this._parametroMultiplo_ != null)
        {
            this._parametroMultiplo_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._parametroMultiplo_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._parametroMultiplo_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._parametroMultiplo_ == child)
        {
            this._parametroMultiplo_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._parametroMultiplo_ == oldChild)
        {
            setParametroMultiplo((PParametroMultiplo) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
