/* This file was generated by SableCC (http://www.sablecc.org/). */

package cmu.node;

import cmu.analysis.*;

@SuppressWarnings("nls")
public final class AMenosTermoUnario extends PTermoUnario
{
    private TSub _sub_;
    private PTermoUnario _termoUnario_;

    public AMenosTermoUnario()
    {
        // Constructor
    }

    public AMenosTermoUnario(
        @SuppressWarnings("hiding") TSub _sub_,
        @SuppressWarnings("hiding") PTermoUnario _termoUnario_)
    {
        // Constructor
        setSub(_sub_);

        setTermoUnario(_termoUnario_);

    }

    @Override
    public Object clone()
    {
        return new AMenosTermoUnario(
            cloneNode(this._sub_),
            cloneNode(this._termoUnario_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAMenosTermoUnario(this);
    }

    public TSub getSub()
    {
        return this._sub_;
    }

    public void setSub(TSub node)
    {
        if(this._sub_ != null)
        {
            this._sub_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._sub_ = node;
    }

    public PTermoUnario getTermoUnario()
    {
        return this._termoUnario_;
    }

    public void setTermoUnario(PTermoUnario node)
    {
        if(this._termoUnario_ != null)
        {
            this._termoUnario_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._termoUnario_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._sub_)
            + toString(this._termoUnario_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._sub_ == child)
        {
            this._sub_ = null;
            return;
        }

        if(this._termoUnario_ == child)
        {
            this._termoUnario_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._sub_ == oldChild)
        {
            setSub((TSub) newChild);
            return;
        }

        if(this._termoUnario_ == oldChild)
        {
            setTermoUnario((PTermoUnario) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
