/* This file was generated by SableCC (http://www.sablecc.org/). */

package cmu.node;

import cmu.analysis.*;

@SuppressWarnings("nls")
public final class AMenosExpUnario extends PExpUnario
{
    private TSub _sub_;
    private PExpUnario _expUnario_;

    public AMenosExpUnario()
    {
        // Constructor
    }

    public AMenosExpUnario(
        @SuppressWarnings("hiding") TSub _sub_,
        @SuppressWarnings("hiding") PExpUnario _expUnario_)
    {
        // Constructor
        setSub(_sub_);

        setExpUnario(_expUnario_);

    }

    @Override
    public Object clone()
    {
        return new AMenosExpUnario(
            cloneNode(this._sub_),
            cloneNode(this._expUnario_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAMenosExpUnario(this);
    }

    public TSub getSub()
    {
        return this._sub_;
    }

    public void setSub(TSub node)
    {
        if(this._sub_ != null)
        {
            this._sub_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._sub_ = node;
    }

    public PExpUnario getExpUnario()
    {
        return this._expUnario_;
    }

    public void setExpUnario(PExpUnario node)
    {
        if(this._expUnario_ != null)
        {
            this._expUnario_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expUnario_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._sub_)
            + toString(this._expUnario_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._sub_ == child)
        {
            this._sub_ = null;
            return;
        }

        if(this._expUnario_ == child)
        {
            this._expUnario_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._sub_ == oldChild)
        {
            setSub((TSub) newChild);
            return;
        }

        if(this._expUnario_ == oldChild)
        {
            setExpUnario((PExpUnario) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
