/* This file was generated by SableCC (http://www.sablecc.org/). */

package cmu.node;

import cmu.analysis.*;

@SuppressWarnings("nls")
public final class AModTermoFator extends PTermoFator
{
    private PTermoFator _termoFator_;
    private TMod _mod_;
    private PTermoUnario _termoUnario_;

    public AModTermoFator()
    {
        // Constructor
    }

    public AModTermoFator(
        @SuppressWarnings("hiding") PTermoFator _termoFator_,
        @SuppressWarnings("hiding") TMod _mod_,
        @SuppressWarnings("hiding") PTermoUnario _termoUnario_)
    {
        // Constructor
        setTermoFator(_termoFator_);

        setMod(_mod_);

        setTermoUnario(_termoUnario_);

    }

    @Override
    public Object clone()
    {
        return new AModTermoFator(
            cloneNode(this._termoFator_),
            cloneNode(this._mod_),
            cloneNode(this._termoUnario_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAModTermoFator(this);
    }

    public PTermoFator getTermoFator()
    {
        return this._termoFator_;
    }

    public void setTermoFator(PTermoFator node)
    {
        if(this._termoFator_ != null)
        {
            this._termoFator_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._termoFator_ = node;
    }

    public TMod getMod()
    {
        return this._mod_;
    }

    public void setMod(TMod node)
    {
        if(this._mod_ != null)
        {
            this._mod_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._mod_ = node;
    }

    public PTermoUnario getTermoUnario()
    {
        return this._termoUnario_;
    }

    public void setTermoUnario(PTermoUnario node)
    {
        if(this._termoUnario_ != null)
        {
            this._termoUnario_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._termoUnario_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._termoFator_)
            + toString(this._mod_)
            + toString(this._termoUnario_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._termoFator_ == child)
        {
            this._termoFator_ = null;
            return;
        }

        if(this._mod_ == child)
        {
            this._mod_ = null;
            return;
        }

        if(this._termoUnario_ == child)
        {
            this._termoUnario_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._termoFator_ == oldChild)
        {
            setTermoFator((PTermoFator) newChild);
            return;
        }

        if(this._mod_ == oldChild)
        {
            setMod((TMod) newChild);
            return;
        }

        if(this._termoUnario_ == oldChild)
        {
            setTermoUnario((PTermoUnario) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
