/* This file was generated by SableCC (http://www.sablecc.org/). */

package cmu.node;

import cmu.analysis.*;

@SuppressWarnings("nls")
public final class AModExpFator extends PExpFator
{
    private PExpFator _expFator_;
    private TMod _mod_;
    private PExpUnario _expUnario_;

    public AModExpFator()
    {
        // Constructor
    }

    public AModExpFator(
        @SuppressWarnings("hiding") PExpFator _expFator_,
        @SuppressWarnings("hiding") TMod _mod_,
        @SuppressWarnings("hiding") PExpUnario _expUnario_)
    {
        // Constructor
        setExpFator(_expFator_);

        setMod(_mod_);

        setExpUnario(_expUnario_);

    }

    @Override
    public Object clone()
    {
        return new AModExpFator(
            cloneNode(this._expFator_),
            cloneNode(this._mod_),
            cloneNode(this._expUnario_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAModExpFator(this);
    }

    public PExpFator getExpFator()
    {
        return this._expFator_;
    }

    public void setExpFator(PExpFator node)
    {
        if(this._expFator_ != null)
        {
            this._expFator_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expFator_ = node;
    }

    public TMod getMod()
    {
        return this._mod_;
    }

    public void setMod(TMod node)
    {
        if(this._mod_ != null)
        {
            this._mod_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._mod_ = node;
    }

    public PExpUnario getExpUnario()
    {
        return this._expUnario_;
    }

    public void setExpUnario(PExpUnario node)
    {
        if(this._expUnario_ != null)
        {
            this._expUnario_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expUnario_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._expFator_)
            + toString(this._mod_)
            + toString(this._expUnario_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._expFator_ == child)
        {
            this._expFator_ = null;
            return;
        }

        if(this._mod_ == child)
        {
            this._mod_ = null;
            return;
        }

        if(this._expUnario_ == child)
        {
            this._expUnario_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._expFator_ == oldChild)
        {
            setExpFator((PExpFator) newChild);
            return;
        }

        if(this._mod_ == oldChild)
        {
            setMod((TMod) newChild);
            return;
        }

        if(this._expUnario_ == oldChild)
        {
            setExpUnario((PExpUnario) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
