/* This file was generated by SableCC (http://www.sablecc.org/). */

package cmu.node;

import cmu.analysis.*;

@SuppressWarnings("nls")
public final class AMultiplaDecFuncaoLista extends PDecFuncaoLista
{
    private PDecFuncaoLista _decFuncaoLista_;
    private PDecFuncao _decFuncao_;

    public AMultiplaDecFuncaoLista()
    {
        // Constructor
    }

    public AMultiplaDecFuncaoLista(
        @SuppressWarnings("hiding") PDecFuncaoLista _decFuncaoLista_,
        @SuppressWarnings("hiding") PDecFuncao _decFuncao_)
    {
        // Constructor
        setDecFuncaoLista(_decFuncaoLista_);

        setDecFuncao(_decFuncao_);

    }

    @Override
    public Object clone()
    {
        return new AMultiplaDecFuncaoLista(
            cloneNode(this._decFuncaoLista_),
            cloneNode(this._decFuncao_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAMultiplaDecFuncaoLista(this);
    }

    public PDecFuncaoLista getDecFuncaoLista()
    {
        return this._decFuncaoLista_;
    }

    public void setDecFuncaoLista(PDecFuncaoLista node)
    {
        if(this._decFuncaoLista_ != null)
        {
            this._decFuncaoLista_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._decFuncaoLista_ = node;
    }

    public PDecFuncao getDecFuncao()
    {
        return this._decFuncao_;
    }

    public void setDecFuncao(PDecFuncao node)
    {
        if(this._decFuncao_ != null)
        {
            this._decFuncao_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._decFuncao_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._decFuncaoLista_)
            + toString(this._decFuncao_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._decFuncaoLista_ == child)
        {
            this._decFuncaoLista_ = null;
            return;
        }

        if(this._decFuncao_ == child)
        {
            this._decFuncao_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._decFuncaoLista_ == oldChild)
        {
            setDecFuncaoLista((PDecFuncaoLista) newChild);
            return;
        }

        if(this._decFuncao_ == oldChild)
        {
            setDecFuncao((PDecFuncao) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
