/* This file was generated by SableCC (http://www.sablecc.org/). */

package cmu.node;

import cmu.analysis.*;

@SuppressWarnings("nls")
public final class ANaoExpUnario extends PExpUnario
{
    private TNao _nao_;
    private TEsqPar _esqPar_;
    private PExp _exp_;
    private TDirPar _dirPar_;

    public ANaoExpUnario()
    {
        // Constructor
    }

    public ANaoExpUnario(
        @SuppressWarnings("hiding") TNao _nao_,
        @SuppressWarnings("hiding") TEsqPar _esqPar_,
        @SuppressWarnings("hiding") PExp _exp_,
        @SuppressWarnings("hiding") TDirPar _dirPar_)
    {
        // Constructor
        setNao(_nao_);

        setEsqPar(_esqPar_);

        setExp(_exp_);

        setDirPar(_dirPar_);

    }

    @Override
    public Object clone()
    {
        return new ANaoExpUnario(
            cloneNode(this._nao_),
            cloneNode(this._esqPar_),
            cloneNode(this._exp_),
            cloneNode(this._dirPar_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseANaoExpUnario(this);
    }

    public TNao getNao()
    {
        return this._nao_;
    }

    public void setNao(TNao node)
    {
        if(this._nao_ != null)
        {
            this._nao_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._nao_ = node;
    }

    public TEsqPar getEsqPar()
    {
        return this._esqPar_;
    }

    public void setEsqPar(TEsqPar node)
    {
        if(this._esqPar_ != null)
        {
            this._esqPar_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._esqPar_ = node;
    }

    public PExp getExp()
    {
        return this._exp_;
    }

    public void setExp(PExp node)
    {
        if(this._exp_ != null)
        {
            this._exp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._exp_ = node;
    }

    public TDirPar getDirPar()
    {
        return this._dirPar_;
    }

    public void setDirPar(TDirPar node)
    {
        if(this._dirPar_ != null)
        {
            this._dirPar_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._dirPar_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._nao_)
            + toString(this._esqPar_)
            + toString(this._exp_)
            + toString(this._dirPar_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._nao_ == child)
        {
            this._nao_ = null;
            return;
        }

        if(this._esqPar_ == child)
        {
            this._esqPar_ = null;
            return;
        }

        if(this._exp_ == child)
        {
            this._exp_ = null;
            return;
        }

        if(this._dirPar_ == child)
        {
            this._dirPar_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._nao_ == oldChild)
        {
            setNao((TNao) newChild);
            return;
        }

        if(this._esqPar_ == oldChild)
        {
            setEsqPar((TEsqPar) newChild);
            return;
        }

        if(this._exp_ == oldChild)
        {
            setExp((PExp) newChild);
            return;
        }

        if(this._dirPar_ == oldChild)
        {
            setDirPar((TDirPar) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
