/* This file was generated by SableCC (http://www.sablecc.org/). */

package cmu.node;

import cmu.analysis.*;

@SuppressWarnings("nls")
public final class APadraoOValorProd extends POValorProd
{
    private TOValorDe _oValorDe_;

    public APadraoOValorProd()
    {
        // Constructor
    }

    public APadraoOValorProd(
        @SuppressWarnings("hiding") TOValorDe _oValorDe_)
    {
        // Constructor
        setOValorDe(_oValorDe_);

    }

    @Override
    public Object clone()
    {
        return new APadraoOValorProd(
            cloneNode(this._oValorDe_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAPadraoOValorProd(this);
    }

    public TOValorDe getOValorDe()
    {
        return this._oValorDe_;
    }

    public void setOValorDe(TOValorDe node)
    {
        if(this._oValorDe_ != null)
        {
            this._oValorDe_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._oValorDe_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._oValorDe_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._oValorDe_ == child)
        {
            this._oValorDe_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._oValorDe_ == oldChild)
        {
            setOValorDe((TOValorDe) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
