/* This file was generated by SableCC (http://www.sablecc.org/). */

package cmu.node;

import cmu.analysis.*;

@SuppressWarnings("nls")
public final class AParcialPvaProd extends PPvaProd
{
    private TVoceArranjar _voceArranjar_;

    public AParcialPvaProd()
    {
        // Constructor
    }

    public AParcialPvaProd(
        @SuppressWarnings("hiding") TVoceArranjar _voceArranjar_)
    {
        // Constructor
        setVoceArranjar(_voceArranjar_);

    }

    @Override
    public Object clone()
    {
        return new AParcialPvaProd(
            cloneNode(this._voceArranjar_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAParcialPvaProd(this);
    }

    public TVoceArranjar getVoceArranjar()
    {
        return this._voceArranjar_;
    }

    public void setVoceArranjar(TVoceArranjar node)
    {
        if(this._voceArranjar_ != null)
        {
            this._voceArranjar_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._voceArranjar_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._voceArranjar_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._voceArranjar_ == child)
        {
            this._voceArranjar_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._voceArranjar_ == oldChild)
        {
            setVoceArranjar((TVoceArranjar) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
