/* This file was generated by SableCC (http://www.sablecc.org/). */

package cmu.node;

import cmu.analysis.*;

@SuppressWarnings("nls")
public final class ARecursivoVirgulaParametroLista extends PVirgulaParametroLista
{
    private PVirgulaParametroLista _virgulaParametroLista_;
    private TVirgula _virgula_;
    private PParamGeral _paramGeral_;

    public ARecursivoVirgulaParametroLista()
    {
        // Constructor
    }

    public ARecursivoVirgulaParametroLista(
        @SuppressWarnings("hiding") PVirgulaParametroLista _virgulaParametroLista_,
        @SuppressWarnings("hiding") TVirgula _virgula_,
        @SuppressWarnings("hiding") PParamGeral _paramGeral_)
    {
        // Constructor
        setVirgulaParametroLista(_virgulaParametroLista_);

        setVirgula(_virgula_);

        setParamGeral(_paramGeral_);

    }

    @Override
    public Object clone()
    {
        return new ARecursivoVirgulaParametroLista(
            cloneNode(this._virgulaParametroLista_),
            cloneNode(this._virgula_),
            cloneNode(this._paramGeral_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseARecursivoVirgulaParametroLista(this);
    }

    public PVirgulaParametroLista getVirgulaParametroLista()
    {
        return this._virgulaParametroLista_;
    }

    public void setVirgulaParametroLista(PVirgulaParametroLista node)
    {
        if(this._virgulaParametroLista_ != null)
        {
            this._virgulaParametroLista_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._virgulaParametroLista_ = node;
    }

    public TVirgula getVirgula()
    {
        return this._virgula_;
    }

    public void setVirgula(TVirgula node)
    {
        if(this._virgula_ != null)
        {
            this._virgula_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._virgula_ = node;
    }

    public PParamGeral getParamGeral()
    {
        return this._paramGeral_;
    }

    public void setParamGeral(PParamGeral node)
    {
        if(this._paramGeral_ != null)
        {
            this._paramGeral_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._paramGeral_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._virgulaParametroLista_)
            + toString(this._virgula_)
            + toString(this._paramGeral_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._virgulaParametroLista_ == child)
        {
            this._virgulaParametroLista_ = null;
            return;
        }

        if(this._virgula_ == child)
        {
            this._virgula_ = null;
            return;
        }

        if(this._paramGeral_ == child)
        {
            this._paramGeral_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._virgulaParametroLista_ == oldChild)
        {
            setVirgulaParametroLista((PVirgulaParametroLista) newChild);
            return;
        }

        if(this._virgula_ == oldChild)
        {
            setVirgula((TVirgula) newChild);
            return;
        }

        if(this._paramGeral_ == oldChild)
        {
            setParamGeral((PParamGeral) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
