/* This file was generated by SableCC (http://www.sablecc.org/). */

package cmu.node;

import cmu.analysis.*;

@SuppressWarnings("nls")
public final class AResultadoOValorProd extends POValorProd
{
    private TOResultadoDe _oResultadoDe_;

    public AResultadoOValorProd()
    {
        // Constructor
    }

    public AResultadoOValorProd(
        @SuppressWarnings("hiding") TOResultadoDe _oResultadoDe_)
    {
        // Constructor
        setOResultadoDe(_oResultadoDe_);

    }

    @Override
    public Object clone()
    {
        return new AResultadoOValorProd(
            cloneNode(this._oResultadoDe_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAResultadoOValorProd(this);
    }

    public TOResultadoDe getOResultadoDe()
    {
        return this._oResultadoDe_;
    }

    public void setOResultadoDe(TOResultadoDe node)
    {
        if(this._oResultadoDe_ != null)
        {
            this._oResultadoDe_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._oResultadoDe_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._oResultadoDe_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._oResultadoDe_ == child)
        {
            this._oResultadoDe_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._oResultadoDe_ == oldChild)
        {
            setOResultadoDe((TOResultadoDe) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
