/* This file was generated by SableCC (http://www.sablecc.org/). */

package cmu.node;

import cmu.analysis.*;

@SuppressWarnings("nls")
public final class ASomaTermoAritmetico extends PTermoAritmetico
{
    private PTermoAritmetico _termoAritmetico_;
    private TSoma _soma_;
    private PTermoFator _termoFator_;

    public ASomaTermoAritmetico()
    {
        // Constructor
    }

    public ASomaTermoAritmetico(
        @SuppressWarnings("hiding") PTermoAritmetico _termoAritmetico_,
        @SuppressWarnings("hiding") TSoma _soma_,
        @SuppressWarnings("hiding") PTermoFator _termoFator_)
    {
        // Constructor
        setTermoAritmetico(_termoAritmetico_);

        setSoma(_soma_);

        setTermoFator(_termoFator_);

    }

    @Override
    public Object clone()
    {
        return new ASomaTermoAritmetico(
            cloneNode(this._termoAritmetico_),
            cloneNode(this._soma_),
            cloneNode(this._termoFator_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASomaTermoAritmetico(this);
    }

    public PTermoAritmetico getTermoAritmetico()
    {
        return this._termoAritmetico_;
    }

    public void setTermoAritmetico(PTermoAritmetico node)
    {
        if(this._termoAritmetico_ != null)
        {
            this._termoAritmetico_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._termoAritmetico_ = node;
    }

    public TSoma getSoma()
    {
        return this._soma_;
    }

    public void setSoma(TSoma node)
    {
        if(this._soma_ != null)
        {
            this._soma_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._soma_ = node;
    }

    public PTermoFator getTermoFator()
    {
        return this._termoFator_;
    }

    public void setTermoFator(PTermoFator node)
    {
        if(this._termoFator_ != null)
        {
            this._termoFator_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._termoFator_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._termoAritmetico_)
            + toString(this._soma_)
            + toString(this._termoFator_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._termoAritmetico_ == child)
        {
            this._termoAritmetico_ = null;
            return;
        }

        if(this._soma_ == child)
        {
            this._soma_ = null;
            return;
        }

        if(this._termoFator_ == child)
        {
            this._termoFator_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._termoAritmetico_ == oldChild)
        {
            setTermoAritmetico((PTermoAritmetico) newChild);
            return;
        }

        if(this._soma_ == oldChild)
        {
            setSoma((TSoma) newChild);
            return;
        }

        if(this._termoFator_ == oldChild)
        {
            setTermoFator((PTermoFator) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
