/* This file was generated by SableCC (http://www.sablecc.org/). */

package cmu.node;

import cmu.analysis.*;

@SuppressWarnings("nls")
public final class ATernarioTermoBase extends PTermoBase
{
    private PSeTernario _seTernario_;

    public ATernarioTermoBase()
    {
        // Constructor
    }

    public ATernarioTermoBase(
        @SuppressWarnings("hiding") PSeTernario _seTernario_)
    {
        // Constructor
        setSeTernario(_seTernario_);

    }

    @Override
    public Object clone()
    {
        return new ATernarioTermoBase(
            cloneNode(this._seTernario_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseATernarioTermoBase(this);
    }

    public PSeTernario getSeTernario()
    {
        return this._seTernario_;
    }

    public void setSeTernario(PSeTernario node)
    {
        if(this._seTernario_ != null)
        {
            this._seTernario_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._seTernario_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._seTernario_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._seTernario_ == child)
        {
            this._seTernario_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._seTernario_ == oldChild)
        {
            setSeTernario((PSeTernario) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
