/* This file was generated by SableCC (http://www.sablecc.org/). */

package cmu.node;

import cmu.analysis.*;

@SuppressWarnings("nls")
public final class AUnarioTermoFator extends PTermoFator
{
    private PTermoUnario _termoUnario_;

    public AUnarioTermoFator()
    {
        // Constructor
    }

    public AUnarioTermoFator(
        @SuppressWarnings("hiding") PTermoUnario _termoUnario_)
    {
        // Constructor
        setTermoUnario(_termoUnario_);

    }

    @Override
    public Object clone()
    {
        return new AUnarioTermoFator(
            cloneNode(this._termoUnario_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAUnarioTermoFator(this);
    }

    public PTermoUnario getTermoUnario()
    {
        return this._termoUnario_;
    }

    public void setTermoUnario(PTermoUnario node)
    {
        if(this._termoUnario_ != null)
        {
            this._termoUnario_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._termoUnario_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._termoUnario_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._termoUnario_ == child)
        {
            this._termoUnario_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._termoUnario_ == oldChild)
        {
            setTermoUnario((PTermoUnario) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
