/* This file was generated by SableCC (http://www.sablecc.org/). */

package cmu.node;

import cmu.analysis.*;

@SuppressWarnings("nls")
public final class AUnicoDecConstantes extends PDecConstantes
{
    private PDecConstante _decConstante_;

    public AUnicoDecConstantes()
    {
        // Constructor
    }

    public AUnicoDecConstantes(
        @SuppressWarnings("hiding") PDecConstante _decConstante_)
    {
        // Constructor
        setDecConstante(_decConstante_);

    }

    @Override
    public Object clone()
    {
        return new AUnicoDecConstantes(
            cloneNode(this._decConstante_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAUnicoDecConstantes(this);
    }

    public PDecConstante getDecConstante()
    {
        return this._decConstante_;
    }

    public void setDecConstante(PDecConstante node)
    {
        if(this._decConstante_ != null)
        {
            this._decConstante_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._decConstante_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._decConstante_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._decConstante_ == child)
        {
            this._decConstante_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._decConstante_ == oldChild)
        {
            setDecConstante((PDecConstante) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
