/* This file was generated by SableCC (http://www.sablecc.org/). */

package cmu.node;

import cmu.analysis.*;

@SuppressWarnings("nls")
public final class AUnicoVirgulaConstLista extends PVirgulaConstLista
{
    private TVirgula _virgula_;
    private PDecConstante _decConstante_;

    public AUnicoVirgulaConstLista()
    {
        // Constructor
    }

    public AUnicoVirgulaConstLista(
        @SuppressWarnings("hiding") TVirgula _virgula_,
        @SuppressWarnings("hiding") PDecConstante _decConstante_)
    {
        // Constructor
        setVirgula(_virgula_);

        setDecConstante(_decConstante_);

    }

    @Override
    public Object clone()
    {
        return new AUnicoVirgulaConstLista(
            cloneNode(this._virgula_),
            cloneNode(this._decConstante_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAUnicoVirgulaConstLista(this);
    }

    public TVirgula getVirgula()
    {
        return this._virgula_;
    }

    public void setVirgula(TVirgula node)
    {
        if(this._virgula_ != null)
        {
            this._virgula_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._virgula_ = node;
    }

    public PDecConstante getDecConstante()
    {
        return this._decConstante_;
    }

    public void setDecConstante(PDecConstante node)
    {
        if(this._decConstante_ != null)
        {
            this._decConstante_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._decConstante_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._virgula_)
            + toString(this._decConstante_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._virgula_ == child)
        {
            this._virgula_ = null;
            return;
        }

        if(this._decConstante_ == child)
        {
            this._decConstante_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._virgula_ == oldChild)
        {
            setVirgula((TVirgula) newChild);
            return;
        }

        if(this._decConstante_ == oldChild)
        {
            setDecConstante((PDecConstante) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
