/* This file was generated by SableCC (http://www.sablecc.org/). */

package cmu.node;

import cmu.analysis.*;

@SuppressWarnings("nls")
public final class AUnicoVirgulaPaLista extends PVirgulaPaLista
{
    private TVirgula _virgula_;
    private PParamGeral _paramGeral_;

    public AUnicoVirgulaPaLista()
    {
        // Constructor
    }

    public AUnicoVirgulaPaLista(
        @SuppressWarnings("hiding") TVirgula _virgula_,
        @SuppressWarnings("hiding") PParamGeral _paramGeral_)
    {
        // Constructor
        setVirgula(_virgula_);

        setParamGeral(_paramGeral_);

    }

    @Override
    public Object clone()
    {
        return new AUnicoVirgulaPaLista(
            cloneNode(this._virgula_),
            cloneNode(this._paramGeral_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAUnicoVirgulaPaLista(this);
    }

    public TVirgula getVirgula()
    {
        return this._virgula_;
    }

    public void setVirgula(TVirgula node)
    {
        if(this._virgula_ != null)
        {
            this._virgula_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._virgula_ = node;
    }

    public PParamGeral getParamGeral()
    {
        return this._paramGeral_;
    }

    public void setParamGeral(PParamGeral node)
    {
        if(this._paramGeral_ != null)
        {
            this._paramGeral_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._paramGeral_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._virgula_)
            + toString(this._paramGeral_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._virgula_ == child)
        {
            this._virgula_ = null;
            return;
        }

        if(this._paramGeral_ == child)
        {
            this._paramGeral_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._virgula_ == oldChild)
        {
            setVirgula((TVirgula) newChild);
            return;
        }

        if(this._paramGeral_ == oldChild)
        {
            setParamGeral((PParamGeral) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
