/* This file was generated by SableCC (http://www.sablecc.org/). */

package cmu.node;

import cmu.analysis.*;

@SuppressWarnings("nls")
public final class TAFuncao extends Token
{
    public TAFuncao()
    {
        super.setText("A funcao");
    }

    public TAFuncao(int line, int pos)
    {
        super.setText("A funcao");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TAFuncao(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTAFuncao(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TAFuncao text.");
    }
}
