/* This file was generated by SableCC (http://www.sablecc.org/). */

package cmu.node;

import cmu.analysis.*;

@SuppressWarnings("nls")
public final class TArruma extends Token
{
    public TArruma()
    {
        super.setText("arruma");
    }

    public TArruma(int line, int pos)
    {
        super.setText("arruma");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TArruma(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTArruma(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TArruma text.");
    }
}
