/* This file was generated by SableCC (http://www.sablecc.org/). */

package cmu.node;

import cmu.analysis.*;

@SuppressWarnings("nls")
public final class TAtencao extends Token
{
    public TAtencao()
    {
        super.setText("atencao");
    }

    public TAtencao(int line, int pos)
    {
        super.setText("atencao");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TAtencao(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTAtencao(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TAtencao text.");
    }
}
