/* This file was generated by SableCC (http://www.sablecc.org/). */

package cmu.node;

import cmu.analysis.*;

@SuppressWarnings("nls")
public final class TComoValor extends Token
{
    public TComoValor()
    {
        super.setText("como valor");
    }

    public TComoValor(int line, int pos)
    {
        super.setText("como valor");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TComoValor(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTComoValor(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TComoValor text.");
    }
}
