/* This file was generated by SableCC (http://www.sablecc.org/). */

package cmu.node;

import cmu.analysis.*;

@SuppressWarnings("nls")
public final class TEmTrocaDe extends Token
{
    public TEmTrocaDe()
    {
        super.setText("em troca de");
    }

    public TEmTrocaDe(int line, int pos)
    {
        super.setText("em troca de");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TEmTrocaDe(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTEmTrocaDe(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TEmTrocaDe text.");
    }
}
