/* This file was generated by SableCC (http://www.sablecc.org/). */

package cmu.node;

import cmu.analysis.*;

@SuppressWarnings("nls")
public final class TFavor extends Token
{
    public TFavor()
    {
        super.setText("favor");
    }

    public TFavor(int line, int pos)
    {
        super.setText("favor");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TFavor(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTFavor(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TFavor text.");
    }
}
