/* This file was generated by SableCC (http://www.sablecc.org/). */

package cmu.node;

import cmu.analysis.*;

@SuppressWarnings("nls")
public final class TInicioConstantes extends Token
{
    public TInicioConstantes()
    {
        super.setText("Ja ia esquecendo... preste atencao, por favor:");
    }

    public TInicioConstantes(int line, int pos)
    {
        super.setText("Ja ia esquecendo... preste atencao, por favor:");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TInicioConstantes(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTInicioConstantes(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TInicioConstantes text.");
    }
}
