/* This file was generated by SableCC (http://www.sablecc.org/). */

package cmu.node;

import cmu.analysis.*;

@SuppressWarnings("nls")
public final class TOResultadoDe extends Token
{
    public TOResultadoDe()
    {
        super.setText("o resultado de");
    }

    public TOResultadoDe(int line, int pos)
    {
        super.setText("o resultado de");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TOResultadoDe(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTOResultadoDe(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TOResultadoDe text.");
    }
}
