/* This file was generated by SableCC (http://www.sablecc.org/). */

package cmu.node;

import cmu.analysis.*;

@SuppressWarnings("nls")
public final class TParaEla extends Token
{
    public TParaEla()
    {
        super.setText(", para ela,");
    }

    public TParaEla(int line, int pos)
    {
        super.setText(", para ela,");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TParaEla(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTParaEla(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TParaEla text.");
    }
}
