/* This file was generated by SableCC (http://www.sablecc.org/). */

package cmu.analysis;

import java.util.*;
import cmu.node.*;

public class ReversedDepthFirstAdapter extends AnalysisAdapter
{
    public void inStart(Start node)
    {
        defaultIn(node);
    }

    public void outStart(Start node)
    {
        defaultOut(node);
    }

    public void defaultIn(@SuppressWarnings("unused") Node node)
    {
        // Do nothing
    }

    public void defaultOut(@SuppressWarnings("unused") Node node)
    {
        // Do nothing
    }

    @Override
    public void caseStart(Start node)
    {
        inStart(node);
        node.getEOF().apply(this);
        node.getPPrograma().apply(this);
        outStart(node);
    }

    public void inAListaPrograma(AListaPrograma node)
    {
        defaultIn(node);
    }

    public void outAListaPrograma(AListaPrograma node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAListaPrograma(AListaPrograma node)
    {
        inAListaPrograma(node);
        {
            List<PDecFuncao> copy = new ArrayList<PDecFuncao>(node.getDecFuncao());
            Collections.reverse(copy);
            for(PDecFuncao e : copy)
            {
                e.apply(this);
            }
        }
        outAListaPrograma(node);
    }

    public void inADecFuncao(ADecFuncao node)
    {
        defaultIn(node);
    }

    public void outADecFuncao(ADecFuncao node)
    {
        defaultOut(node);
    }

    @Override
    public void caseADecFuncao(ADecFuncao node)
    {
        inADecFuncao(node);
        if(node.getP2() != null)
        {
            node.getP2().apply(this);
        }
        if(node.getElaIraTeRetornar() != null)
        {
            node.getElaIraTeRetornar().apply(this);
        }
        if(node.getSecaoConstantes() != null)
        {
            node.getSecaoConstantes().apply(this);
        }
        if(node.getExpRetorno() != null)
        {
            node.getExpRetorno().apply(this);
        }
        if(node.getOValorDe() != null)
        {
            node.getOValorDe().apply(this);
        }
        if(node.getV2() != null)
        {
            node.getV2().apply(this);
        }
        if(node.getParaVoceArranjar() != null)
        {
            node.getParaVoceArranjar().apply(this);
        }
        if(node.getV1() != null)
        {
            node.getV1().apply(this);
        }
        if(node.getParametros() != null)
        {
            node.getParametros().apply(this);
        }
        if(node.getSeCond() != null)
        {
            node.getSeCond().apply(this);
        }
        if(node.getP1() != null)
        {
            node.getP1().apply(this);
        }
        if(node.getTipo() != null)
        {
            node.getTipo().apply(this);
        }
        if(node.getArruma() != null)
        {
            node.getArruma().apply(this);
        }
        if(node.getId() != null)
        {
            node.getId().apply(this);
        }
        if(node.getAFuncao() != null)
        {
            node.getAFuncao().apply(this);
        }
        if(node.getMarcador() != null)
        {
            node.getMarcador().apply(this);
        }
        outADecFuncao(node);
    }

    public void inANumeroTipo(ANumeroTipo node)
    {
        defaultIn(node);
    }

    public void outANumeroTipo(ANumeroTipo node)
    {
        defaultOut(node);
    }

    @Override
    public void caseANumeroTipo(ANumeroTipo node)
    {
        inANumeroTipo(node);
        if(node.getTipoNum() != null)
        {
            node.getTipoNum().apply(this);
        }
        outANumeroTipo(node);
    }

    public void inARespostaTipo(ARespostaTipo node)
    {
        defaultIn(node);
    }

    public void outARespostaTipo(ARespostaTipo node)
    {
        defaultOut(node);
    }

    @Override
    public void caseARespostaTipo(ARespostaTipo node)
    {
        inARespostaTipo(node);
        if(node.getTipoBool() != null)
        {
            node.getTipoBool().apply(this);
        }
        outARespostaTipo(node);
    }

    public void inANadaTipo(ANadaTipo node)
    {
        defaultIn(node);
    }

    public void outANadaTipo(ANadaTipo node)
    {
        defaultOut(node);
    }

    @Override
    public void caseANadaTipo(ANadaTipo node)
    {
        inANadaTipo(node);
        if(node.getTipoNada() != null)
        {
            node.getTipoNada().apply(this);
        }
        outANadaTipo(node);
    }

    public void inAUnicoParametros(AUnicoParametros node)
    {
        defaultIn(node);
    }

    public void outAUnicoParametros(AUnicoParametros node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAUnicoParametros(AUnicoParametros node)
    {
        inAUnicoParametros(node);
        if(node.getParamGeral() != null)
        {
            node.getParamGeral().apply(this);
        }
        outAUnicoParametros(node);
    }

    public void inAListaParametros(AListaParametros node)
    {
        defaultIn(node);
    }

    public void outAListaParametros(AListaParametros node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAListaParametros(AListaParametros node)
    {
        inAListaParametros(node);
        if(node.getParametroMultiplo() != null)
        {
            node.getParametroMultiplo().apply(this);
        }
        outAListaParametros(node);
    }

    public void inADeclaracaoParamGeral(ADeclaracaoParamGeral node)
    {
        defaultIn(node);
    }

    public void outADeclaracaoParamGeral(ADeclaracaoParamGeral node)
    {
        defaultOut(node);
    }

    @Override
    public void caseADeclaracaoParamGeral(ADeclaracaoParamGeral node)
    {
        inADeclaracaoParamGeral(node);
        if(node.getNome() != null)
        {
            node.getNome().apply(this);
        }
        if(node.getTipo() != null)
        {
            node.getTipo().apply(this);
        }
        outADeclaracaoParamGeral(node);
    }

    public void inAAssinaturaParamGeral(AAssinaturaParamGeral node)
    {
        defaultIn(node);
    }

    public void outAAssinaturaParamGeral(AAssinaturaParamGeral node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAAssinaturaParamGeral(AAssinaturaParamGeral node)
    {
        inAAssinaturaParamGeral(node);
        if(node.getAssinatura() != null)
        {
            node.getAssinatura().apply(this);
        }
        outAAssinaturaParamGeral(node);
    }

    public void inADuploParametroMultiplo(ADuploParametroMultiplo node)
    {
        defaultIn(node);
    }

    public void outADuploParametroMultiplo(ADuploParametroMultiplo node)
    {
        defaultOut(node);
    }

    @Override
    public void caseADuploParametroMultiplo(ADuploParametroMultiplo node)
    {
        inADuploParametroMultiplo(node);
        if(node.getP2() != null)
        {
            node.getP2().apply(this);
        }
        if(node.getEConn() != null)
        {
            node.getEConn().apply(this);
        }
        if(node.getP1() != null)
        {
            node.getP1().apply(this);
        }
        outADuploParametroMultiplo(node);
    }

    public void inATriploOuMaisParametroMultiplo(ATriploOuMaisParametroMultiplo node)
    {
        defaultIn(node);
    }

    public void outATriploOuMaisParametroMultiplo(ATriploOuMaisParametroMultiplo node)
    {
        defaultOut(node);
    }

    @Override
    public void caseATriploOuMaisParametroMultiplo(ATriploOuMaisParametroMultiplo node)
    {
        inATriploOuMaisParametroMultiplo(node);
        if(node.getP2() != null)
        {
            node.getP2().apply(this);
        }
        if(node.getEConn() != null)
        {
            node.getEConn().apply(this);
        }
        if(node.getVirgulaParametroLista() != null)
        {
            node.getVirgulaParametroLista().apply(this);
        }
        if(node.getP1() != null)
        {
            node.getP1().apply(this);
        }
        outATriploOuMaisParametroMultiplo(node);
    }

    public void inAUnicoVirgulaParametroLista(AUnicoVirgulaParametroLista node)
    {
        defaultIn(node);
    }

    public void outAUnicoVirgulaParametroLista(AUnicoVirgulaParametroLista node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAUnicoVirgulaParametroLista(AUnicoVirgulaParametroLista node)
    {
        inAUnicoVirgulaParametroLista(node);
        if(node.getParamGeral() != null)
        {
            node.getParamGeral().apply(this);
        }
        if(node.getVirgula() != null)
        {
            node.getVirgula().apply(this);
        }
        outAUnicoVirgulaParametroLista(node);
    }

    public void inARecursivoVirgulaParametroLista(ARecursivoVirgulaParametroLista node)
    {
        defaultIn(node);
    }

    public void outARecursivoVirgulaParametroLista(ARecursivoVirgulaParametroLista node)
    {
        defaultOut(node);
    }

    @Override
    public void caseARecursivoVirgulaParametroLista(ARecursivoVirgulaParametroLista node)
    {
        inARecursivoVirgulaParametroLista(node);
        if(node.getParamGeral() != null)
        {
            node.getParamGeral().apply(this);
        }
        if(node.getVirgula() != null)
        {
            node.getVirgula().apply(this);
        }
        if(node.getVirgulaParametroLista() != null)
        {
            node.getVirgulaParametroLista().apply(this);
        }
        outARecursivoVirgulaParametroLista(node);
    }

    public void inAAssinatura(AAssinatura node)
    {
        defaultIn(node);
    }

    public void outAAssinatura(AAssinatura node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAAssinatura(AAssinatura node)
    {
        inAAssinatura(node);
        if(node.getDirPar() != null)
        {
            node.getDirPar().apply(this);
        }
        if(node.getParametrosAssinatura() != null)
        {
            node.getParametrosAssinatura().apply(this);
        }
        if(node.getEmTrocaDe() != null)
        {
            node.getEmTrocaDe().apply(this);
        }
        if(node.getTipo() != null)
        {
            node.getTipo().apply(this);
        }
        if(node.getQueArruma() != null)
        {
            node.getQueArruma().apply(this);
        }
        if(node.getEsqPar() != null)
        {
            node.getEsqPar().apply(this);
        }
        if(node.getId() != null)
        {
            node.getId().apply(this);
        }
        if(node.getUmaFuncao() != null)
        {
            node.getUmaFuncao().apply(this);
        }
        outAAssinatura(node);
    }

    public void inAUnicoParametrosAssinatura(AUnicoParametrosAssinatura node)
    {
        defaultIn(node);
    }

    public void outAUnicoParametrosAssinatura(AUnicoParametrosAssinatura node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAUnicoParametrosAssinatura(AUnicoParametrosAssinatura node)
    {
        inAUnicoParametrosAssinatura(node);
        if(node.getParamGeral() != null)
        {
            node.getParamGeral().apply(this);
        }
        outAUnicoParametrosAssinatura(node);
    }

    public void inAListaParametrosAssinatura(AListaParametrosAssinatura node)
    {
        defaultIn(node);
    }

    public void outAListaParametrosAssinatura(AListaParametrosAssinatura node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAListaParametrosAssinatura(AListaParametrosAssinatura node)
    {
        inAListaParametrosAssinatura(node);
        if(node.getParametroAssinaturaMultiplo() != null)
        {
            node.getParametroAssinaturaMultiplo().apply(this);
        }
        outAListaParametrosAssinatura(node);
    }

    public void inADuploParametroAssinaturaMultiplo(ADuploParametroAssinaturaMultiplo node)
    {
        defaultIn(node);
    }

    public void outADuploParametroAssinaturaMultiplo(ADuploParametroAssinaturaMultiplo node)
    {
        defaultOut(node);
    }

    @Override
    public void caseADuploParametroAssinaturaMultiplo(ADuploParametroAssinaturaMultiplo node)
    {
        inADuploParametroAssinaturaMultiplo(node);
        if(node.getP2() != null)
        {
            node.getP2().apply(this);
        }
        if(node.getEConn() != null)
        {
            node.getEConn().apply(this);
        }
        if(node.getP1() != null)
        {
            node.getP1().apply(this);
        }
        outADuploParametroAssinaturaMultiplo(node);
    }

    public void inATriploOuMaisParametroAssinaturaMultiplo(ATriploOuMaisParametroAssinaturaMultiplo node)
    {
        defaultIn(node);
    }

    public void outATriploOuMaisParametroAssinaturaMultiplo(ATriploOuMaisParametroAssinaturaMultiplo node)
    {
        defaultOut(node);
    }

    @Override
    public void caseATriploOuMaisParametroAssinaturaMultiplo(ATriploOuMaisParametroAssinaturaMultiplo node)
    {
        inATriploOuMaisParametroAssinaturaMultiplo(node);
        if(node.getP2() != null)
        {
            node.getP2().apply(this);
        }
        if(node.getEConn() != null)
        {
            node.getEConn().apply(this);
        }
        if(node.getVirgulaPaLista() != null)
        {
            node.getVirgulaPaLista().apply(this);
        }
        if(node.getP1() != null)
        {
            node.getP1().apply(this);
        }
        outATriploOuMaisParametroAssinaturaMultiplo(node);
    }

    public void inAUnicoVirgulaPaLista(AUnicoVirgulaPaLista node)
    {
        defaultIn(node);
    }

    public void outAUnicoVirgulaPaLista(AUnicoVirgulaPaLista node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAUnicoVirgulaPaLista(AUnicoVirgulaPaLista node)
    {
        inAUnicoVirgulaPaLista(node);
        if(node.getParamGeral() != null)
        {
            node.getParamGeral().apply(this);
        }
        if(node.getVirgula() != null)
        {
            node.getVirgula().apply(this);
        }
        outAUnicoVirgulaPaLista(node);
    }

    public void inARecursivoVirgulaPaLista(ARecursivoVirgulaPaLista node)
    {
        defaultIn(node);
    }

    public void outARecursivoVirgulaPaLista(ARecursivoVirgulaPaLista node)
    {
        defaultOut(node);
    }

    @Override
    public void caseARecursivoVirgulaPaLista(ARecursivoVirgulaPaLista node)
    {
        inARecursivoVirgulaPaLista(node);
        if(node.getParamGeral() != null)
        {
            node.getParamGeral().apply(this);
        }
        if(node.getVirgula() != null)
        {
            node.getVirgula().apply(this);
        }
        if(node.getVirgulaPaLista() != null)
        {
            node.getVirgulaPaLista().apply(this);
        }
        outARecursivoVirgulaPaLista(node);
    }

    public void inAPadraoExpRetorno(APadraoExpRetorno node)
    {
        defaultIn(node);
    }

    public void outAPadraoExpRetorno(APadraoExpRetorno node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAPadraoExpRetorno(APadraoExpRetorno node)
    {
        inAPadraoExpRetorno(node);
        if(node.getExp() != null)
        {
            node.getExp().apply(this);
        }
        outAPadraoExpRetorno(node);
    }

    public void inACondicaoTernariaExpRetorno(ACondicaoTernariaExpRetorno node)
    {
        defaultIn(node);
    }

    public void outACondicaoTernariaExpRetorno(ACondicaoTernariaExpRetorno node)
    {
        defaultOut(node);
    }

    @Override
    public void caseACondicaoTernariaExpRetorno(ACondicaoTernariaExpRetorno node)
    {
        inACondicaoTernariaExpRetorno(node);
        if(node.getCondicaoTernaria() != null)
        {
            node.getCondicaoTernaria().apply(this);
        }
        outACondicaoTernariaExpRetorno(node);
    }

    public void inACondicaoTernaria(ACondicaoTernaria node)
    {
        defaultIn(node);
    }

    public void outACondicaoTernaria(ACondicaoTernaria node)
    {
        defaultOut(node);
    }

    @Override
    public void caseACondicaoTernaria(ACondicaoTernaria node)
    {
        inACondicaoTernaria(node);
        if(node.getSeTernario() != null)
        {
            node.getSeTernario().apply(this);
        }
        if(node.getUmaCondicaoAssim() != null)
        {
            node.getUmaCondicaoAssim().apply(this);
        }
        outACondicaoTernaria(node);
    }

    public void inATernarioExp(ATernarioExp node)
    {
        defaultIn(node);
    }

    public void outATernarioExp(ATernarioExp node)
    {
        defaultOut(node);
    }

    @Override
    public void caseATernarioExp(ATernarioExp node)
    {
        inATernarioExp(node);
        if(node.getSeTernario() != null)
        {
            node.getSeTernario().apply(this);
        }
        outATernarioExp(node);
    }

    public void inADisjuncaoExp(ADisjuncaoExp node)
    {
        defaultIn(node);
    }

    public void outADisjuncaoExp(ADisjuncaoExp node)
    {
        defaultOut(node);
    }

    @Override
    public void caseADisjuncaoExp(ADisjuncaoExp node)
    {
        inADisjuncaoExp(node);
        if(node.getExpDisjuncao() != null)
        {
            node.getExpDisjuncao().apply(this);
        }
        outADisjuncaoExp(node);
    }

    public void inASeTernario(ASeTernario node)
    {
        defaultIn(node);
    }

    public void outASeTernario(ASeTernario node)
    {
        defaultOut(node);
    }

    @Override
    public void caseASeTernario(ASeTernario node)
    {
        inASeTernario(node);
        if(node.getFalso() != null)
        {
            node.getFalso().apply(this);
        }
        if(node.getSenao() != null)
        {
            node.getSenao().apply(this);
        }
        if(node.getVerd() != null)
        {
            node.getVerd().apply(this);
        }
        if(node.getEntao() != null)
        {
            node.getEntao().apply(this);
        }
        if(node.getDirPar() != null)
        {
            node.getDirPar().apply(this);
        }
        if(node.getCond() != null)
        {
            node.getCond().apply(this);
        }
        if(node.getEsqPar() != null)
        {
            node.getEsqPar().apply(this);
        }
        if(node.getSe() != null)
        {
            node.getSe().apply(this);
        }
        outASeTernario(node);
    }

    public void inAOuExpDisjuncao(AOuExpDisjuncao node)
    {
        defaultIn(node);
    }

    public void outAOuExpDisjuncao(AOuExpDisjuncao node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAOuExpDisjuncao(AOuExpDisjuncao node)
    {
        inAOuExpDisjuncao(node);
        if(node.getExpConjuncao() != null)
        {
            node.getExpConjuncao().apply(this);
        }
        if(node.getOu() != null)
        {
            node.getOu().apply(this);
        }
        if(node.getExpDisjuncao() != null)
        {
            node.getExpDisjuncao().apply(this);
        }
        outAOuExpDisjuncao(node);
    }

    public void inAConjuncaoExpDisjuncao(AConjuncaoExpDisjuncao node)
    {
        defaultIn(node);
    }

    public void outAConjuncaoExpDisjuncao(AConjuncaoExpDisjuncao node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAConjuncaoExpDisjuncao(AConjuncaoExpDisjuncao node)
    {
        inAConjuncaoExpDisjuncao(node);
        if(node.getExpConjuncao() != null)
        {
            node.getExpConjuncao().apply(this);
        }
        outAConjuncaoExpDisjuncao(node);
    }

    public void inAEExpConjuncao(AEExpConjuncao node)
    {
        defaultIn(node);
    }

    public void outAEExpConjuncao(AEExpConjuncao node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAEExpConjuncao(AEExpConjuncao node)
    {
        inAEExpConjuncao(node);
        if(node.getExpRelacional() != null)
        {
            node.getExpRelacional().apply(this);
        }
        if(node.getEConn() != null)
        {
            node.getEConn().apply(this);
        }
        if(node.getExpConjuncao() != null)
        {
            node.getExpConjuncao().apply(this);
        }
        outAEExpConjuncao(node);
    }

    public void inARelacionalExpConjuncao(ARelacionalExpConjuncao node)
    {
        defaultIn(node);
    }

    public void outARelacionalExpConjuncao(ARelacionalExpConjuncao node)
    {
        defaultOut(node);
    }

    @Override
    public void caseARelacionalExpConjuncao(ARelacionalExpConjuncao node)
    {
        inARelacionalExpConjuncao(node);
        if(node.getExpRelacional() != null)
        {
            node.getExpRelacional().apply(this);
        }
        outARelacionalExpConjuncao(node);
    }

    public void inAIgualExpRelacional(AIgualExpRelacional node)
    {
        defaultIn(node);
    }

    public void outAIgualExpRelacional(AIgualExpRelacional node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAIgualExpRelacional(AIgualExpRelacional node)
    {
        inAIgualExpRelacional(node);
        if(node.getExpAritmetica() != null)
        {
            node.getExpAritmetica().apply(this);
        }
        if(node.getIgual() != null)
        {
            node.getIgual().apply(this);
        }
        if(node.getExpRelacional() != null)
        {
            node.getExpRelacional().apply(this);
        }
        outAIgualExpRelacional(node);
    }

    public void inAMaiorExpRelacional(AMaiorExpRelacional node)
    {
        defaultIn(node);
    }

    public void outAMaiorExpRelacional(AMaiorExpRelacional node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAMaiorExpRelacional(AMaiorExpRelacional node)
    {
        inAMaiorExpRelacional(node);
        if(node.getExpAritmetica() != null)
        {
            node.getExpAritmetica().apply(this);
        }
        if(node.getMaior() != null)
        {
            node.getMaior().apply(this);
        }
        if(node.getExpRelacional() != null)
        {
            node.getExpRelacional().apply(this);
        }
        outAMaiorExpRelacional(node);
    }

    public void inAMenorExpRelacional(AMenorExpRelacional node)
    {
        defaultIn(node);
    }

    public void outAMenorExpRelacional(AMenorExpRelacional node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAMenorExpRelacional(AMenorExpRelacional node)
    {
        inAMenorExpRelacional(node);
        if(node.getExpAritmetica() != null)
        {
            node.getExpAritmetica().apply(this);
        }
        if(node.getMenor() != null)
        {
            node.getMenor().apply(this);
        }
        if(node.getExpRelacional() != null)
        {
            node.getExpRelacional().apply(this);
        }
        outAMenorExpRelacional(node);
    }

    public void inAMaiorIgualExpRelacional(AMaiorIgualExpRelacional node)
    {
        defaultIn(node);
    }

    public void outAMaiorIgualExpRelacional(AMaiorIgualExpRelacional node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAMaiorIgualExpRelacional(AMaiorIgualExpRelacional node)
    {
        inAMaiorIgualExpRelacional(node);
        if(node.getExpAritmetica() != null)
        {
            node.getExpAritmetica().apply(this);
        }
        if(node.getMaiorIgual() != null)
        {
            node.getMaiorIgual().apply(this);
        }
        if(node.getExpRelacional() != null)
        {
            node.getExpRelacional().apply(this);
        }
        outAMaiorIgualExpRelacional(node);
    }

    public void inAMenorIgualExpRelacional(AMenorIgualExpRelacional node)
    {
        defaultIn(node);
    }

    public void outAMenorIgualExpRelacional(AMenorIgualExpRelacional node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAMenorIgualExpRelacional(AMenorIgualExpRelacional node)
    {
        inAMenorIgualExpRelacional(node);
        if(node.getExpAritmetica() != null)
        {
            node.getExpAritmetica().apply(this);
        }
        if(node.getMenorIgual() != null)
        {
            node.getMenorIgual().apply(this);
        }
        if(node.getExpRelacional() != null)
        {
            node.getExpRelacional().apply(this);
        }
        outAMenorIgualExpRelacional(node);
    }

    public void inAAritmeticaExpRelacional(AAritmeticaExpRelacional node)
    {
        defaultIn(node);
    }

    public void outAAritmeticaExpRelacional(AAritmeticaExpRelacional node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAAritmeticaExpRelacional(AAritmeticaExpRelacional node)
    {
        inAAritmeticaExpRelacional(node);
        if(node.getExpAritmetica() != null)
        {
            node.getExpAritmetica().apply(this);
        }
        outAAritmeticaExpRelacional(node);
    }

    public void inASomaExpAritmetica(ASomaExpAritmetica node)
    {
        defaultIn(node);
    }

    public void outASomaExpAritmetica(ASomaExpAritmetica node)
    {
        defaultOut(node);
    }

    @Override
    public void caseASomaExpAritmetica(ASomaExpAritmetica node)
    {
        inASomaExpAritmetica(node);
        if(node.getExpFator() != null)
        {
            node.getExpFator().apply(this);
        }
        if(node.getSoma() != null)
        {
            node.getSoma().apply(this);
        }
        if(node.getExpAritmetica() != null)
        {
            node.getExpAritmetica().apply(this);
        }
        outASomaExpAritmetica(node);
    }

    public void inASubExpAritmetica(ASubExpAritmetica node)
    {
        defaultIn(node);
    }

    public void outASubExpAritmetica(ASubExpAritmetica node)
    {
        defaultOut(node);
    }

    @Override
    public void caseASubExpAritmetica(ASubExpAritmetica node)
    {
        inASubExpAritmetica(node);
        if(node.getExpFator() != null)
        {
            node.getExpFator().apply(this);
        }
        if(node.getSub() != null)
        {
            node.getSub().apply(this);
        }
        if(node.getExpAritmetica() != null)
        {
            node.getExpAritmetica().apply(this);
        }
        outASubExpAritmetica(node);
    }

    public void inAFatorExpAritmetica(AFatorExpAritmetica node)
    {
        defaultIn(node);
    }

    public void outAFatorExpAritmetica(AFatorExpAritmetica node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAFatorExpAritmetica(AFatorExpAritmetica node)
    {
        inAFatorExpAritmetica(node);
        if(node.getExpFator() != null)
        {
            node.getExpFator().apply(this);
        }
        outAFatorExpAritmetica(node);
    }

    public void inAMultExpFator(AMultExpFator node)
    {
        defaultIn(node);
    }

    public void outAMultExpFator(AMultExpFator node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAMultExpFator(AMultExpFator node)
    {
        inAMultExpFator(node);
        if(node.getExpUnario() != null)
        {
            node.getExpUnario().apply(this);
        }
        if(node.getMult() != null)
        {
            node.getMult().apply(this);
        }
        if(node.getExpFator() != null)
        {
            node.getExpFator().apply(this);
        }
        outAMultExpFator(node);
    }

    public void inADivExpFator(ADivExpFator node)
    {
        defaultIn(node);
    }

    public void outADivExpFator(ADivExpFator node)
    {
        defaultOut(node);
    }

    @Override
    public void caseADivExpFator(ADivExpFator node)
    {
        inADivExpFator(node);
        if(node.getExpUnario() != null)
        {
            node.getExpUnario().apply(this);
        }
        if(node.getDiv() != null)
        {
            node.getDiv().apply(this);
        }
        if(node.getExpFator() != null)
        {
            node.getExpFator().apply(this);
        }
        outADivExpFator(node);
    }

    public void inAModExpFator(AModExpFator node)
    {
        defaultIn(node);
    }

    public void outAModExpFator(AModExpFator node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAModExpFator(AModExpFator node)
    {
        inAModExpFator(node);
        if(node.getExpUnario() != null)
        {
            node.getExpUnario().apply(this);
        }
        if(node.getMod() != null)
        {
            node.getMod().apply(this);
        }
        if(node.getExpFator() != null)
        {
            node.getExpFator().apply(this);
        }
        outAModExpFator(node);
    }

    public void inAUnarioExpFator(AUnarioExpFator node)
    {
        defaultIn(node);
    }

    public void outAUnarioExpFator(AUnarioExpFator node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAUnarioExpFator(AUnarioExpFator node)
    {
        inAUnarioExpFator(node);
        if(node.getExpUnario() != null)
        {
            node.getExpUnario().apply(this);
        }
        outAUnarioExpFator(node);
    }

    public void inAMenosExpUnario(AMenosExpUnario node)
    {
        defaultIn(node);
    }

    public void outAMenosExpUnario(AMenosExpUnario node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAMenosExpUnario(AMenosExpUnario node)
    {
        inAMenosExpUnario(node);
        if(node.getExpUnario() != null)
        {
            node.getExpUnario().apply(this);
        }
        if(node.getSub() != null)
        {
            node.getSub().apply(this);
        }
        outAMenosExpUnario(node);
    }

    public void inANaoExpUnario(ANaoExpUnario node)
    {
        defaultIn(node);
    }

    public void outANaoExpUnario(ANaoExpUnario node)
    {
        defaultOut(node);
    }

    @Override
    public void caseANaoExpUnario(ANaoExpUnario node)
    {
        inANaoExpUnario(node);
        if(node.getDirPar() != null)
        {
            node.getDirPar().apply(this);
        }
        if(node.getExp() != null)
        {
            node.getExp().apply(this);
        }
        if(node.getEsqPar() != null)
        {
            node.getEsqPar().apply(this);
        }
        if(node.getNao() != null)
        {
            node.getNao().apply(this);
        }
        outANaoExpUnario(node);
    }

    public void inABaseExpUnario(ABaseExpUnario node)
    {
        defaultIn(node);
    }

    public void outABaseExpUnario(ABaseExpUnario node)
    {
        defaultOut(node);
    }

    @Override
    public void caseABaseExpUnario(ABaseExpUnario node)
    {
        inABaseExpUnario(node);
        if(node.getExpBase() != null)
        {
            node.getExpBase().apply(this);
        }
        outABaseExpUnario(node);
    }

    public void inAIntExpBase(AIntExpBase node)
    {
        defaultIn(node);
    }

    public void outAIntExpBase(AIntExpBase node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAIntExpBase(AIntExpBase node)
    {
        inAIntExpBase(node);
        if(node.getNumInt() != null)
        {
            node.getNumInt().apply(this);
        }
        outAIntExpBase(node);
    }

    public void inARealExpBase(ARealExpBase node)
    {
        defaultIn(node);
    }

    public void outARealExpBase(ARealExpBase node)
    {
        defaultOut(node);
    }

    @Override
    public void caseARealExpBase(ARealExpBase node)
    {
        inARealExpBase(node);
        if(node.getNumReal() != null)
        {
            node.getNumReal().apply(this);
        }
        outARealExpBase(node);
    }

    public void inASimExpBase(ASimExpBase node)
    {
        defaultIn(node);
    }

    public void outASimExpBase(ASimExpBase node)
    {
        defaultOut(node);
    }

    @Override
    public void caseASimExpBase(ASimExpBase node)
    {
        inASimExpBase(node);
        if(node.getSim() != null)
        {
            node.getSim().apply(this);
        }
        outASimExpBase(node);
    }

    public void inANaoValExpBase(ANaoValExpBase node)
    {
        defaultIn(node);
    }

    public void outANaoValExpBase(ANaoValExpBase node)
    {
        defaultOut(node);
    }

    @Override
    public void caseANaoValExpBase(ANaoValExpBase node)
    {
        inANaoValExpBase(node);
        if(node.getNao() != null)
        {
            node.getNao().apply(this);
        }
        outANaoValExpBase(node);
    }

    public void inAIdExpBase(AIdExpBase node)
    {
        defaultIn(node);
    }

    public void outAIdExpBase(AIdExpBase node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAIdExpBase(AIdExpBase node)
    {
        inAIdExpBase(node);
        if(node.getId() != null)
        {
            node.getId().apply(this);
        }
        outAIdExpBase(node);
    }

    public void inAChamadaExpBase(AChamadaExpBase node)
    {
        defaultIn(node);
    }

    public void outAChamadaExpBase(AChamadaExpBase node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAChamadaExpBase(AChamadaExpBase node)
    {
        inAChamadaExpBase(node);
        if(node.getChamada() != null)
        {
            node.getChamada().apply(this);
        }
        outAChamadaExpBase(node);
    }

    public void inAParExpBase(AParExpBase node)
    {
        defaultIn(node);
    }

    public void outAParExpBase(AParExpBase node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAParExpBase(AParExpBase node)
    {
        inAParExpBase(node);
        if(node.getDirPar() != null)
        {
            node.getDirPar().apply(this);
        }
        if(node.getExp() != null)
        {
            node.getExp().apply(this);
        }
        if(node.getEsqPar() != null)
        {
            node.getEsqPar().apply(this);
        }
        outAParExpBase(node);
    }

    public void inAChamada(AChamada node)
    {
        defaultIn(node);
    }

    public void outAChamada(AChamada node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAChamada(AChamada node)
    {
        inAChamada(node);
        if(node.getDirCol() != null)
        {
            node.getDirCol().apply(this);
        }
        if(node.getListaExp() != null)
        {
            node.getListaExp().apply(this);
        }
        if(node.getEsqCol() != null)
        {
            node.getEsqCol().apply(this);
        }
        if(node.getId() != null)
        {
            node.getId().apply(this);
        }
        outAChamada(node);
    }

    public void inAVazioListaExp(AVazioListaExp node)
    {
        defaultIn(node);
    }

    public void outAVazioListaExp(AVazioListaExp node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAVazioListaExp(AVazioListaExp node)
    {
        inAVazioListaExp(node);
        outAVazioListaExp(node);
    }

    public void inAElementosListaExp(AElementosListaExp node)
    {
        defaultIn(node);
    }

    public void outAElementosListaExp(AElementosListaExp node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAElementosListaExp(AElementosListaExp node)
    {
        inAElementosListaExp(node);
        if(node.getListaExpElems() != null)
        {
            node.getListaExpElems().apply(this);
        }
        outAElementosListaExp(node);
    }

    public void inAUnicoListaExpElems(AUnicoListaExpElems node)
    {
        defaultIn(node);
    }

    public void outAUnicoListaExpElems(AUnicoListaExpElems node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAUnicoListaExpElems(AUnicoListaExpElems node)
    {
        inAUnicoListaExpElems(node);
        if(node.getExp() != null)
        {
            node.getExp().apply(this);
        }
        outAUnicoListaExpElems(node);
    }

    public void inAVariosListaExpElems(AVariosListaExpElems node)
    {
        defaultIn(node);
    }

    public void outAVariosListaExpElems(AVariosListaExpElems node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAVariosListaExpElems(AVariosListaExpElems node)
    {
        inAVariosListaExpElems(node);
        if(node.getExp() != null)
        {
            node.getExp().apply(this);
        }
        if(node.getBarra() != null)
        {
            node.getBarra().apply(this);
        }
        if(node.getListaExpElems() != null)
        {
            node.getListaExpElems().apply(this);
        }
        outAVariosListaExpElems(node);
    }

    public void inASecaoConstantes(ASecaoConstantes node)
    {
        defaultIn(node);
    }

    public void outASecaoConstantes(ASecaoConstantes node)
    {
        defaultOut(node);
    }

    @Override
    public void caseASecaoConstantes(ASecaoConstantes node)
    {
        inASecaoConstantes(node);
        if(node.getDecConstantes() != null)
        {
            node.getDecConstantes().apply(this);
        }
        outASecaoConstantes(node);
    }

    public void inAUnicoDecConstantes(AUnicoDecConstantes node)
    {
        defaultIn(node);
    }

    public void outAUnicoDecConstantes(AUnicoDecConstantes node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAUnicoDecConstantes(AUnicoDecConstantes node)
    {
        inAUnicoDecConstantes(node);
        if(node.getDecConstante() != null)
        {
            node.getDecConstante().apply(this);
        }
        outAUnicoDecConstantes(node);
    }

    public void inADuploDecConstantes(ADuploDecConstantes node)
    {
        defaultIn(node);
    }

    public void outADuploDecConstantes(ADuploDecConstantes node)
    {
        defaultOut(node);
    }

    @Override
    public void caseADuploDecConstantes(ADuploDecConstantes node)
    {
        inADuploDecConstantes(node);
        if(node.getD2() != null)
        {
            node.getD2().apply(this);
        }
        if(node.getEConn() != null)
        {
            node.getEConn().apply(this);
        }
        if(node.getD1() != null)
        {
            node.getD1().apply(this);
        }
        outADuploDecConstantes(node);
    }

    public void inATriploOuMaisDecConstantes(ATriploOuMaisDecConstantes node)
    {
        defaultIn(node);
    }

    public void outATriploOuMaisDecConstantes(ATriploOuMaisDecConstantes node)
    {
        defaultOut(node);
    }

    @Override
    public void caseATriploOuMaisDecConstantes(ATriploOuMaisDecConstantes node)
    {
        inATriploOuMaisDecConstantes(node);
        if(node.getD2() != null)
        {
            node.getD2().apply(this);
        }
        if(node.getEConn() != null)
        {
            node.getEConn().apply(this);
        }
        if(node.getVirgulaConstLista() != null)
        {
            node.getVirgulaConstLista().apply(this);
        }
        if(node.getD1() != null)
        {
            node.getD1().apply(this);
        }
        outATriploOuMaisDecConstantes(node);
    }

    public void inAUnicoVirgulaConstLista(AUnicoVirgulaConstLista node)
    {
        defaultIn(node);
    }

    public void outAUnicoVirgulaConstLista(AUnicoVirgulaConstLista node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAUnicoVirgulaConstLista(AUnicoVirgulaConstLista node)
    {
        inAUnicoVirgulaConstLista(node);
        if(node.getDecConstante() != null)
        {
            node.getDecConstante().apply(this);
        }
        if(node.getVirgula() != null)
        {
            node.getVirgula().apply(this);
        }
        outAUnicoVirgulaConstLista(node);
    }

    public void inARecursivoVirgulaConstLista(ARecursivoVirgulaConstLista node)
    {
        defaultIn(node);
    }

    public void outARecursivoVirgulaConstLista(ARecursivoVirgulaConstLista node)
    {
        defaultOut(node);
    }

    @Override
    public void caseARecursivoVirgulaConstLista(ARecursivoVirgulaConstLista node)
    {
        inARecursivoVirgulaConstLista(node);
        if(node.getDecConstante() != null)
        {
            node.getDecConstante().apply(this);
        }
        if(node.getVirgula() != null)
        {
            node.getVirgula().apply(this);
        }
        if(node.getVirgulaConstLista() != null)
        {
            node.getVirgulaConstLista().apply(this);
        }
        outARecursivoVirgulaConstLista(node);
    }

    public void inADecConstante(ADecConstante node)
    {
        defaultIn(node);
    }

    public void outADecConstante(ADecConstante node)
    {
        defaultOut(node);
    }

    @Override
    public void caseADecConstante(ADecConstante node)
    {
        inADecConstante(node);
        if(node.getComoValor() != null)
        {
            node.getComoValor().apply(this);
        }
        if(node.getExp() != null)
        {
            node.getExp().apply(this);
        }
        if(node.getQueTem() != null)
        {
            node.getQueTem().apply(this);
        }
        if(node.getTipo() != null)
        {
            node.getTipo().apply(this);
        }
        if(node.getDizSer() != null)
        {
            node.getDizSer().apply(this);
        }
        if(node.getId() != null)
        {
            node.getId().apply(this);
        }
        outADecConstante(node);
    }
}
