/* This file was generated by SableCC (http://www.sablecc.org/). */

package cmu.parser;

import cmu.analysis.AnalysisAdapter;
import cmu.node.*;

class TokenIndex extends AnalysisAdapter
{
    int index;

    @Override
    public void caseTJa(@SuppressWarnings("unused") TJa node)
    {
        this.index = 0;
    }

    @Override
    public void caseTIa(@SuppressWarnings("unused") TIa node)
    {
        this.index = 1;
    }

    @Override
    public void caseTEsquecendo(@SuppressWarnings("unused") TEsquecendo node)
    {
        this.index = 2;
    }

    @Override
    public void caseTTresPontos(@SuppressWarnings("unused") TTresPontos node)
    {
        this.index = 3;
    }

    @Override
    public void caseTPreste(@SuppressWarnings("unused") TPreste node)
    {
        this.index = 4;
    }

    @Override
    public void caseTAtencao(@SuppressWarnings("unused") TAtencao node)
    {
        this.index = 5;
    }

    @Override
    public void caseTPor(@SuppressWarnings("unused") TPor node)
    {
        this.index = 6;
    }

    @Override
    public void caseTFavor(@SuppressWarnings("unused") TFavor node)
    {
        this.index = 7;
    }

    @Override
    public void caseTDizSer(@SuppressWarnings("unused") TDizSer node)
    {
        this.index = 8;
    }

    @Override
    public void caseTQueTem(@SuppressWarnings("unused") TQueTem node)
    {
        this.index = 9;
    }

    @Override
    public void caseTComoValor(@SuppressWarnings("unused") TComoValor node)
    {
        this.index = 10;
    }

    @Override
    public void caseTEConn(@SuppressWarnings("unused") TEConn node)
    {
        this.index = 11;
    }

    @Override
    public void caseTCom(@SuppressWarnings("unused") TCom node)
    {
        this.index = 12;
    }

    @Override
    public void caseTAFuncao(@SuppressWarnings("unused") TAFuncao node)
    {
        this.index = 13;
    }

    @Override
    public void caseTArruma(@SuppressWarnings("unused") TArruma node)
    {
        this.index = 14;
    }

    @Override
    public void caseTPonto(@SuppressWarnings("unused") TPonto node)
    {
        this.index = 15;
    }

    @Override
    public void caseTVirgula(@SuppressWarnings("unused") TVirgula node)
    {
        this.index = 16;
    }

    @Override
    public void caseTSeCond(@SuppressWarnings("unused") TSeCond node)
    {
        this.index = 17;
    }

    @Override
    public void caseTParaVoceArranjar(@SuppressWarnings("unused") TParaVoceArranjar node)
    {
        this.index = 18;
    }

    @Override
    public void caseTOValorDe(@SuppressWarnings("unused") TOValorDe node)
    {
        this.index = 19;
    }

    @Override
    public void caseTElaIraTeRetornar(@SuppressWarnings("unused") TElaIraTeRetornar node)
    {
        this.index = 20;
    }

    @Override
    public void caseTMarcadorInicio(@SuppressWarnings("unused") TMarcadorInicio node)
    {
        this.index = 21;
    }

    @Override
    public void caseTTipoNum(@SuppressWarnings("unused") TTipoNum node)
    {
        this.index = 22;
    }

    @Override
    public void caseTTipoBool(@SuppressWarnings("unused") TTipoBool node)
    {
        this.index = 23;
    }

    @Override
    public void caseTTipoNada(@SuppressWarnings("unused") TTipoNada node)
    {
        this.index = 24;
    }

    @Override
    public void caseTSe(@SuppressWarnings("unused") TSe node)
    {
        this.index = 25;
    }

    @Override
    public void caseTEntao(@SuppressWarnings("unused") TEntao node)
    {
        this.index = 26;
    }

    @Override
    public void caseTSenao(@SuppressWarnings("unused") TSenao node)
    {
        this.index = 27;
    }

    @Override
    public void caseTUmaFuncao(@SuppressWarnings("unused") TUmaFuncao node)
    {
        this.index = 28;
    }

    @Override
    public void caseTQueArruma(@SuppressWarnings("unused") TQueArruma node)
    {
        this.index = 29;
    }

    @Override
    public void caseTEmTrocaDe(@SuppressWarnings("unused") TEmTrocaDe node)
    {
        this.index = 30;
    }

    @Override
    public void caseTSim(@SuppressWarnings("unused") TSim node)
    {
        this.index = 31;
    }

    @Override
    public void caseTNao(@SuppressWarnings("unused") TNao node)
    {
        this.index = 32;
    }

    @Override
    public void caseTSoma(@SuppressWarnings("unused") TSoma node)
    {
        this.index = 33;
    }

    @Override
    public void caseTSub(@SuppressWarnings("unused") TSub node)
    {
        this.index = 34;
    }

    @Override
    public void caseTMult(@SuppressWarnings("unused") TMult node)
    {
        this.index = 35;
    }

    @Override
    public void caseTDiv(@SuppressWarnings("unused") TDiv node)
    {
        this.index = 36;
    }

    @Override
    public void caseTMod(@SuppressWarnings("unused") TMod node)
    {
        this.index = 37;
    }

    @Override
    public void caseTMaiorIgual(@SuppressWarnings("unused") TMaiorIgual node)
    {
        this.index = 38;
    }

    @Override
    public void caseTMenorIgual(@SuppressWarnings("unused") TMenorIgual node)
    {
        this.index = 39;
    }

    @Override
    public void caseTMaior(@SuppressWarnings("unused") TMaior node)
    {
        this.index = 40;
    }

    @Override
    public void caseTMenor(@SuppressWarnings("unused") TMenor node)
    {
        this.index = 41;
    }

    @Override
    public void caseTIgual(@SuppressWarnings("unused") TIgual node)
    {
        this.index = 42;
    }

    @Override
    public void caseTOu(@SuppressWarnings("unused") TOu node)
    {
        this.index = 43;
    }

    @Override
    public void caseTEsqPar(@SuppressWarnings("unused") TEsqPar node)
    {
        this.index = 44;
    }

    @Override
    public void caseTDirPar(@SuppressWarnings("unused") TDirPar node)
    {
        this.index = 45;
    }

    @Override
    public void caseTEsqCol(@SuppressWarnings("unused") TEsqCol node)
    {
        this.index = 46;
    }

    @Override
    public void caseTDirCol(@SuppressWarnings("unused") TDirCol node)
    {
        this.index = 47;
    }

    @Override
    public void caseTBarra(@SuppressWarnings("unused") TBarra node)
    {
        this.index = 48;
    }

    @Override
    public void caseTDoisPontos(@SuppressWarnings("unused") TDoisPontos node)
    {
        this.index = 49;
    }

    @Override
    public void caseTPontoVirgula(@SuppressWarnings("unused") TPontoVirgula node)
    {
        this.index = 50;
    }

    @Override
    public void caseTUmaCondicaoAssim(@SuppressWarnings("unused") TUmaCondicaoAssim node)
    {
        this.index = 51;
    }

    @Override
    public void caseTId(@SuppressWarnings("unused") TId node)
    {
        this.index = 52;
    }

    @Override
    public void caseTNumInt(@SuppressWarnings("unused") TNumInt node)
    {
        this.index = 53;
    }

    @Override
    public void caseTNumReal(@SuppressWarnings("unused") TNumReal node)
    {
        this.index = 54;
    }

    @Override
    public void caseEOF(@SuppressWarnings("unused") EOF node)
    {
        this.index = 55;
    }
}
