/* This file was generated by SableCC (http://www.sablecc.org/). */

package cordelmaisum.node;

import cordelmaisum.analysis.*;

@SuppressWarnings("nls")
public final class TArranjar extends Token
{
    public TArranjar()
    {
        super.setText("arranjar");
    }

    public TArranjar(int line, int pos)
    {
        super.setText("arranjar");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TArranjar(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTArranjar(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TArranjar text.");
    }
}
