/* This file was generated by SableCC (http://www.sablecc.org/). */

package cordelmaisum.node;

import cordelmaisum.analysis.*;

@SuppressWarnings("nls")
public final class TComo extends Token
{
    public TComo()
    {
        super.setText("como");
    }

    public TComo(int line, int pos)
    {
        super.setText("como");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TComo(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTComo(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TComo text.");
    }
}
