/* This file was generated by SableCC (http://www.sablecc.org/). */

package cordelmaisum.node;

import cordelmaisum.analysis.*;

@SuppressWarnings("nls")
public final class TCondicao extends Token
{
    public TCondicao()
    {
        super.setText("condicao");
    }

    public TCondicao(int line, int pos)
    {
        super.setText("condicao");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TCondicao(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTCondicao(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TCondicao text.");
    }
}
