/* This file was generated by SableCC (http://www.sablecc.org/). */

package cordelmaisum.node;

import cordelmaisum.analysis.*;

@SuppressWarnings("nls")
public final class TIra extends Token
{
    public TIra()
    {
        super.setText("ira");
    }

    public TIra(int line, int pos)
    {
        super.setText("ira");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TIra(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTIra(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TIra text.");
    }
}
