/* This file was generated by SableCC (http://www.sablecc.org/). */

package cordelmaisum.node;

import cordelmaisum.analysis.*;

@SuppressWarnings("nls")
public final class TJa extends Token
{
    public TJa()
    {
        super.setText("ja");
    }

    public TJa(int line, int pos)
    {
        super.setText("ja");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TJa(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTJa(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TJa text.");
    }
}
