/* This file was generated by SableCC (http://www.sablecc.org/). */

package cordelmaisum.parser;

import cordelmaisum.analysis.AnalysisAdapter;
import cordelmaisum.node.*;

class TokenIndex extends AnalysisAdapter
{
    int index;

    @Override
    public void caseTJa(@SuppressWarnings("unused") TJa node)
    {
        this.index = 0;
    }

    @Override
    public void caseTIa(@SuppressWarnings("unused") TIa node)
    {
        this.index = 1;
    }

    @Override
    public void caseTEsquecendo(@SuppressWarnings("unused") TEsquecendo node)
    {
        this.index = 2;
    }

    @Override
    public void caseTTresPontos(@SuppressWarnings("unused") TTresPontos node)
    {
        this.index = 3;
    }

    @Override
    public void caseTPreste(@SuppressWarnings("unused") TPreste node)
    {
        this.index = 4;
    }

    @Override
    public void caseTAtencao(@SuppressWarnings("unused") TAtencao node)
    {
        this.index = 5;
    }

    @Override
    public void caseTPor(@SuppressWarnings("unused") TPor node)
    {
        this.index = 6;
    }

    @Override
    public void caseTFavor(@SuppressWarnings("unused") TFavor node)
    {
        this.index = 7;
    }

    @Override
    public void caseTDizSer(@SuppressWarnings("unused") TDizSer node)
    {
        this.index = 8;
    }

    @Override
    public void caseTDiz(@SuppressWarnings("unused") TDiz node)
    {
        this.index = 9;
    }

    @Override
    public void caseTSer(@SuppressWarnings("unused") TSer node)
    {
        this.index = 10;
    }

    @Override
    public void caseTQueTem(@SuppressWarnings("unused") TQueTem node)
    {
        this.index = 11;
    }

    @Override
    public void caseTComoValor(@SuppressWarnings("unused") TComoValor node)
    {
        this.index = 12;
    }

    @Override
    public void caseTEConn(@SuppressWarnings("unused") TEConn node)
    {
        this.index = 13;
    }

    @Override
    public void caseTCom(@SuppressWarnings("unused") TCom node)
    {
        this.index = 14;
    }

    @Override
    public void caseTAFuncao(@SuppressWarnings("unused") TAFuncao node)
    {
        this.index = 15;
    }

    @Override
    public void caseTArruma(@SuppressWarnings("unused") TArruma node)
    {
        this.index = 16;
    }

    @Override
    public void caseTPonto(@SuppressWarnings("unused") TPonto node)
    {
        this.index = 17;
    }

    @Override
    public void caseTVirgula(@SuppressWarnings("unused") TVirgula node)
    {
        this.index = 18;
    }

    @Override
    public void caseTSeCond(@SuppressWarnings("unused") TSeCond node)
    {
        this.index = 19;
    }

    @Override
    public void caseTParaEla(@SuppressWarnings("unused") TParaEla node)
    {
        this.index = 20;
    }

    @Override
    public void caseTParaVoceArranjar(@SuppressWarnings("unused") TParaVoceArranjar node)
    {
        this.index = 21;
    }

    @Override
    public void caseTVoceArranjar(@SuppressWarnings("unused") TVoceArranjar node)
    {
        this.index = 22;
    }

    @Override
    public void caseTOValorDe(@SuppressWarnings("unused") TOValorDe node)
    {
        this.index = 23;
    }

    @Override
    public void caseTOResultadoDe(@SuppressWarnings("unused") TOResultadoDe node)
    {
        this.index = 24;
    }

    @Override
    public void caseTElaIraTeRetornar(@SuppressWarnings("unused") TElaIraTeRetornar node)
    {
        this.index = 25;
    }

    @Override
    public void caseTIra(@SuppressWarnings("unused") TIra node)
    {
        this.index = 26;
    }

    @Override
    public void caseTRetornar(@SuppressWarnings("unused") TRetornar node)
    {
        this.index = 27;
    }

    @Override
    public void caseTTe(@SuppressWarnings("unused") TTe node)
    {
        this.index = 28;
    }

    @Override
    public void caseTMarcadorInicio(@SuppressWarnings("unused") TMarcadorInicio node)
    {
        this.index = 29;
    }

    @Override
    public void caseTSua(@SuppressWarnings("unused") TSua node)
    {
        this.index = 30;
    }

    @Override
    public void caseTLicenca(@SuppressWarnings("unused") TLicenca node)
    {
        this.index = 31;
    }

    @Override
    public void caseTAqui(@SuppressWarnings("unused") TAqui node)
    {
        this.index = 32;
    }

    @Override
    public void caseTVamos(@SuppressWarnings("unused") TVamos node)
    {
        this.index = 33;
    }

    @Override
    public void caseTComecar(@SuppressWarnings("unused") TComecar node)
    {
        this.index = 34;
    }

    @Override
    public void caseTExclamacao(@SuppressWarnings("unused") TExclamacao node)
    {
        this.index = 35;
    }

    @Override
    public void caseTTipoNum(@SuppressWarnings("unused") TTipoNum node)
    {
        this.index = 36;
    }

    @Override
    public void caseTTipoBool(@SuppressWarnings("unused") TTipoBool node)
    {
        this.index = 37;
    }

    @Override
    public void caseTTipoNada(@SuppressWarnings("unused") TTipoNada node)
    {
        this.index = 38;
    }

    @Override
    public void caseTNumero(@SuppressWarnings("unused") TNumero node)
    {
        this.index = 39;
    }

    @Override
    public void caseTResposta(@SuppressWarnings("unused") TResposta node)
    {
        this.index = 40;
    }

    @Override
    public void caseTNada(@SuppressWarnings("unused") TNada node)
    {
        this.index = 41;
    }

    @Override
    public void caseTSe(@SuppressWarnings("unused") TSe node)
    {
        this.index = 42;
    }

    @Override
    public void caseTEntao(@SuppressWarnings("unused") TEntao node)
    {
        this.index = 43;
    }

    @Override
    public void caseTSenao(@SuppressWarnings("unused") TSenao node)
    {
        this.index = 44;
    }

    @Override
    public void caseTUmaFuncao(@SuppressWarnings("unused") TUmaFuncao node)
    {
        this.index = 45;
    }

    @Override
    public void caseTFuncao(@SuppressWarnings("unused") TFuncao node)
    {
        this.index = 46;
    }

    @Override
    public void caseTQueArruma(@SuppressWarnings("unused") TQueArruma node)
    {
        this.index = 47;
    }

    @Override
    public void caseTQue(@SuppressWarnings("unused") TQue node)
    {
        this.index = 48;
    }

    @Override
    public void caseTEmTrocaDe(@SuppressWarnings("unused") TEmTrocaDe node)
    {
        this.index = 49;
    }

    @Override
    public void caseTEm(@SuppressWarnings("unused") TEm node)
    {
        this.index = 50;
    }

    @Override
    public void caseTTroca(@SuppressWarnings("unused") TTroca node)
    {
        this.index = 51;
    }

    @Override
    public void caseTEla(@SuppressWarnings("unused") TEla node)
    {
        this.index = 52;
    }

    @Override
    public void caseTDe(@SuppressWarnings("unused") TDe node)
    {
        this.index = 53;
    }

    @Override
    public void caseTSim(@SuppressWarnings("unused") TSim node)
    {
        this.index = 54;
    }

    @Override
    public void caseTNao(@SuppressWarnings("unused") TNao node)
    {
        this.index = 55;
    }

    @Override
    public void caseTTem(@SuppressWarnings("unused") TTem node)
    {
        this.index = 56;
    }

    @Override
    public void caseTValor(@SuppressWarnings("unused") TValor node)
    {
        this.index = 57;
    }

    @Override
    public void caseTPara(@SuppressWarnings("unused") TPara node)
    {
        this.index = 58;
    }

    @Override
    public void caseTVoce(@SuppressWarnings("unused") TVoce node)
    {
        this.index = 59;
    }

    @Override
    public void caseTArranjar(@SuppressWarnings("unused") TArranjar node)
    {
        this.index = 60;
    }

    @Override
    public void caseTComo(@SuppressWarnings("unused") TComo node)
    {
        this.index = 61;
    }

    @Override
    public void caseTO(@SuppressWarnings("unused") TO node)
    {
        this.index = 62;
    }

    @Override
    public void caseTResultado(@SuppressWarnings("unused") TResultado node)
    {
        this.index = 63;
    }

    @Override
    public void caseTSoma(@SuppressWarnings("unused") TSoma node)
    {
        this.index = 64;
    }

    @Override
    public void caseTSub(@SuppressWarnings("unused") TSub node)
    {
        this.index = 65;
    }

    @Override
    public void caseTMult(@SuppressWarnings("unused") TMult node)
    {
        this.index = 66;
    }

    @Override
    public void caseTDiv(@SuppressWarnings("unused") TDiv node)
    {
        this.index = 67;
    }

    @Override
    public void caseTMod(@SuppressWarnings("unused") TMod node)
    {
        this.index = 68;
    }

    @Override
    public void caseTMaiorIgual(@SuppressWarnings("unused") TMaiorIgual node)
    {
        this.index = 69;
    }

    @Override
    public void caseTMenorIgual(@SuppressWarnings("unused") TMenorIgual node)
    {
        this.index = 70;
    }

    @Override
    public void caseTMaior(@SuppressWarnings("unused") TMaior node)
    {
        this.index = 71;
    }

    @Override
    public void caseTMenor(@SuppressWarnings("unused") TMenor node)
    {
        this.index = 72;
    }

    @Override
    public void caseTIgual(@SuppressWarnings("unused") TIgual node)
    {
        this.index = 73;
    }

    @Override
    public void caseTOu(@SuppressWarnings("unused") TOu node)
    {
        this.index = 74;
    }

    @Override
    public void caseTEsqPar(@SuppressWarnings("unused") TEsqPar node)
    {
        this.index = 75;
    }

    @Override
    public void caseTDirPar(@SuppressWarnings("unused") TDirPar node)
    {
        this.index = 76;
    }

    @Override
    public void caseTEsqCol(@SuppressWarnings("unused") TEsqCol node)
    {
        this.index = 77;
    }

    @Override
    public void caseTDirCol(@SuppressWarnings("unused") TDirCol node)
    {
        this.index = 78;
    }

    @Override
    public void caseTBarra(@SuppressWarnings("unused") TBarra node)
    {
        this.index = 79;
    }

    @Override
    public void caseTDoisPontos(@SuppressWarnings("unused") TDoisPontos node)
    {
        this.index = 80;
    }

    @Override
    public void caseTPontoVirgula(@SuppressWarnings("unused") TPontoVirgula node)
    {
        this.index = 81;
    }

    @Override
    public void caseTUmaCondicaoAssim(@SuppressWarnings("unused") TUmaCondicaoAssim node)
    {
        this.index = 82;
    }

    @Override
    public void caseTUma(@SuppressWarnings("unused") TUma node)
    {
        this.index = 83;
    }

    @Override
    public void caseTUm(@SuppressWarnings("unused") TUm node)
    {
        this.index = 84;
    }

    @Override
    public void caseTCondicao(@SuppressWarnings("unused") TCondicao node)
    {
        this.index = 85;
    }

    @Override
    public void caseTAssim(@SuppressWarnings("unused") TAssim node)
    {
        this.index = 86;
    }

    @Override
    public void caseTId(@SuppressWarnings("unused") TId node)
    {
        this.index = 87;
    }

    @Override
    public void caseTNumInt(@SuppressWarnings("unused") TNumInt node)
    {
        this.index = 88;
    }

    @Override
    public void caseTNumReal(@SuppressWarnings("unused") TNumReal node)
    {
        this.index = 89;
    }

    @Override
    public void caseEOF(@SuppressWarnings("unused") EOF node)
    {
        this.index = 90;
    }
}
