/* This file was generated by SableCC (http://www.sablecc.org/). */

package cordelmaisum.analysis;

import cordelmaisum.node.*;

public interface Analysis extends Switch
{
    Object getIn(Node node);
    void setIn(Node node, Object o);
    Object getOut(Node node);
    void setOut(Node node, Object o);

    void caseTCom(TCom node);
    void caseTSua(TSua node);
    void caseTLicenca(TLicenca node);
    void caseTVirgula(TVirgula node);
    void caseTPor(TPor node);
    void caseTAqui(TAqui node);
    void caseTVamos(TVamos node);
    void caseTComecar(TComecar node);
    void caseTExclamacao(TExclamacao node);
    void caseTSeCondicional(TSeCondicional node);
    void caseTSe(TSe node);
    void caseTSenao(TSenao node);
    void caseTEntao(TEntao node);
    void caseTUma(TUma node);
    void caseTCondicao(TCondicao node);
    void caseTAssim(TAssim node);
    void caseTJa(TJa node);
    void caseTIa(TIa node);
    void caseTEsquecendo(TEsquecendo node);
    void caseTPonto(TPonto node);
    void caseTTresPontos(TTresPontos node);
    void caseTPreste(TPreste node);
    void caseTAtencao(TAtencao node);
    void caseTFavor(TFavor node);
    void caseTDoisPontos(TDoisPontos node);
    void caseTDiz(TDiz node);
    void caseTSer(TSer node);
    void caseTQue(TQue node);
    void caseTTem(TTem node);
    void caseTComo(TComo node);
    void caseTValor(TValor node);
    void caseTUm(TUm node);
    void caseTFuncao(TFuncao node);
    void caseTArruma(TArruma node);
    void caseTEm(TEm node);
    void caseTTroca(TTroca node);
    void caseTDe(TDe node);
    void caseTAGrande(TAGrande node);
    void caseTPara(TPara node);
    void caseTEla(TEla node);
    void caseTVoce(TVoce node);
    void caseTArranjar(TArranjar node);
    void caseTO(TO node);
    void caseTIra(TIra node);
    void caseTTe(TTe node);
    void caseTRetornar(TRetornar node);
    void caseTResposta(TResposta node);
    void caseTOperadorAritmetico(TOperadorAritmetico node);
    void caseTSeparador(TSeparador node);
    void caseTOperadorRelacional(TOperadorRelacional node);
    void caseTOperadorBooleano(TOperadorBooleano node);
    void caseTNumeroReal(TNumeroReal node);
    void caseTNumeroInteiro(TNumeroInteiro node);
    void caseTTipo(TTipo node);
    void caseTParEsq(TParEsq node);
    void caseTParDir(TParDir node);
    void caseTColchEsq(TColchEsq node);
    void caseTColchDir(TColchDir node);
    void caseTId(TId node);
    void caseTCommentsBloco(TCommentsBloco node);
    void caseTCommentsLinha(TCommentsLinha node);
    void caseTVazio(TVazio node);
    void caseEOF(EOF node);
    void caseInvalidToken(InvalidToken node);
}
