/* This file was generated by SableCC (http://www.sablecc.org/). */

package cmu.node;

import cmu.analysis.Analysis;

@SuppressWarnings("nls")
public final class ABaseExpUnario extends PExpUnario
{
    private PExpBase _expBase_;

    public ABaseExpUnario()
    {
        // Constructor
    }

    public ABaseExpUnario(
        @SuppressWarnings("hiding") PExpBase _expBase_)
    {
        // Constructor
        setExpBase(_expBase_);

    }

    @Override
    public Object clone()
    {
        return new ABaseExpUnario(
            cloneNode(this._expBase_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseABaseExpUnario(this);
    }

    public PExpBase getExpBase()
    {
        return this._expBase_;
    }

    public void setExpBase(PExpBase node)
    {
        if(this._expBase_ != null)
        {
            this._expBase_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expBase_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._expBase_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._expBase_ == child)
        {
            this._expBase_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._expBase_ == oldChild)
        {
            setExpBase((PExpBase) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
