/* This file was generated by SableCC (http://www.sablecc.org/). */

package cmu.node;

import cmu.analysis.Analysis;

@SuppressWarnings("nls")
public final class ACondicaoTernaria extends PCondicaoTernaria
{
    private TUmaCondicaoAssim _umaCondicaoAssim_;
    private PSeTernario _seTernario_;

    public ACondicaoTernaria()
    {
        // Constructor
    }

    public ACondicaoTernaria(
        @SuppressWarnings("hiding") TUmaCondicaoAssim _umaCondicaoAssim_,
        @SuppressWarnings("hiding") PSeTernario _seTernario_)
    {
        // Constructor
        setUmaCondicaoAssim(_umaCondicaoAssim_);

        setSeTernario(_seTernario_);

    }

    @Override
    public Object clone()
    {
        return new ACondicaoTernaria(
            cloneNode(this._umaCondicaoAssim_),
            cloneNode(this._seTernario_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseACondicaoTernaria(this);
    }

    public TUmaCondicaoAssim getUmaCondicaoAssim()
    {
        return this._umaCondicaoAssim_;
    }

    public void setUmaCondicaoAssim(TUmaCondicaoAssim node)
    {
        if(this._umaCondicaoAssim_ != null)
        {
            this._umaCondicaoAssim_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._umaCondicaoAssim_ = node;
    }

    public PSeTernario getSeTernario()
    {
        return this._seTernario_;
    }

    public void setSeTernario(PSeTernario node)
    {
        if(this._seTernario_ != null)
        {
            this._seTernario_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._seTernario_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._umaCondicaoAssim_)
            + toString(this._seTernario_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._umaCondicaoAssim_ == child)
        {
            this._umaCondicaoAssim_ = null;
            return;
        }

        if(this._seTernario_ == child)
        {
            this._seTernario_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._umaCondicaoAssim_ == oldChild)
        {
            setUmaCondicaoAssim((TUmaCondicaoAssim) newChild);
            return;
        }

        if(this._seTernario_ == oldChild)
        {
            setSeTernario((PSeTernario) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
