/* This file was generated by SableCC (http://www.sablecc.org/). */

package cmu.node;

import cmu.analysis.Analysis;

@SuppressWarnings("nls")
public final class AConjuncaoExpDisjuncao extends PExpDisjuncao
{
    private PExpConjuncao _expConjuncao_;

    public AConjuncaoExpDisjuncao()
    {
        // Constructor
    }

    public AConjuncaoExpDisjuncao(
        @SuppressWarnings("hiding") PExpConjuncao _expConjuncao_)
    {
        // Constructor
        setExpConjuncao(_expConjuncao_);

    }

    @Override
    public Object clone()
    {
        return new AConjuncaoExpDisjuncao(
            cloneNode(this._expConjuncao_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAConjuncaoExpDisjuncao(this);
    }

    public PExpConjuncao getExpConjuncao()
    {
        return this._expConjuncao_;
    }

    public void setExpConjuncao(PExpConjuncao node)
    {
        if(this._expConjuncao_ != null)
        {
            this._expConjuncao_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expConjuncao_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._expConjuncao_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._expConjuncao_ == child)
        {
            this._expConjuncao_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._expConjuncao_ == oldChild)
        {
            setExpConjuncao((PExpConjuncao) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
