/* This file was generated by SableCC (http://www.sablecc.org/). */

package cmu.node;

import cmu.analysis.Analysis;

@SuppressWarnings("nls")
public final class ADecConstante extends PDecConstante
{
    private TId _id_;
    private TDizSer _dizSer_;
    private PTipo _tipo_;
    private TQueTem _queTem_;
    private PExp _exp_;
    private TComoValor _comoValor_;

    public ADecConstante()
    {
        // Constructor
    }

    public ADecConstante(
        @SuppressWarnings("hiding") TId _id_,
        @SuppressWarnings("hiding") TDizSer _dizSer_,
        @SuppressWarnings("hiding") PTipo _tipo_,
        @SuppressWarnings("hiding") TQueTem _queTem_,
        @SuppressWarnings("hiding") PExp _exp_,
        @SuppressWarnings("hiding") TComoValor _comoValor_)
    {
        // Constructor
        setId(_id_);

        setDizSer(_dizSer_);

        setTipo(_tipo_);

        setQueTem(_queTem_);

        setExp(_exp_);

        setComoValor(_comoValor_);

    }

    @Override
    public Object clone()
    {
        return new ADecConstante(
            cloneNode(this._id_),
            cloneNode(this._dizSer_),
            cloneNode(this._tipo_),
            cloneNode(this._queTem_),
            cloneNode(this._exp_),
            cloneNode(this._comoValor_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseADecConstante(this);
    }

    public TId getId()
    {
        return this._id_;
    }

    public void setId(TId node)
    {
        if(this._id_ != null)
        {
            this._id_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._id_ = node;
    }

    public TDizSer getDizSer()
    {
        return this._dizSer_;
    }

    public void setDizSer(TDizSer node)
    {
        if(this._dizSer_ != null)
        {
            this._dizSer_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._dizSer_ = node;
    }

    public PTipo getTipo()
    {
        return this._tipo_;
    }

    public void setTipo(PTipo node)
    {
        if(this._tipo_ != null)
        {
            this._tipo_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._tipo_ = node;
    }

    public TQueTem getQueTem()
    {
        return this._queTem_;
    }

    public void setQueTem(TQueTem node)
    {
        if(this._queTem_ != null)
        {
            this._queTem_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._queTem_ = node;
    }

    public PExp getExp()
    {
        return this._exp_;
    }

    public void setExp(PExp node)
    {
        if(this._exp_ != null)
        {
            this._exp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._exp_ = node;
    }

    public TComoValor getComoValor()
    {
        return this._comoValor_;
    }

    public void setComoValor(TComoValor node)
    {
        if(this._comoValor_ != null)
        {
            this._comoValor_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._comoValor_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._id_)
            + toString(this._dizSer_)
            + toString(this._tipo_)
            + toString(this._queTem_)
            + toString(this._exp_)
            + toString(this._comoValor_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._id_ == child)
        {
            this._id_ = null;
            return;
        }

        if(this._dizSer_ == child)
        {
            this._dizSer_ = null;
            return;
        }

        if(this._tipo_ == child)
        {
            this._tipo_ = null;
            return;
        }

        if(this._queTem_ == child)
        {
            this._queTem_ = null;
            return;
        }

        if(this._exp_ == child)
        {
            this._exp_ = null;
            return;
        }

        if(this._comoValor_ == child)
        {
            this._comoValor_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._id_ == oldChild)
        {
            setId((TId) newChild);
            return;
        }

        if(this._dizSer_ == oldChild)
        {
            setDizSer((TDizSer) newChild);
            return;
        }

        if(this._tipo_ == oldChild)
        {
            setTipo((PTipo) newChild);
            return;
        }

        if(this._queTem_ == oldChild)
        {
            setQueTem((TQueTem) newChild);
            return;
        }

        if(this._exp_ == oldChild)
        {
            setExp((PExp) newChild);
            return;
        }

        if(this._comoValor_ == oldChild)
        {
            setComoValor((TComoValor) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
