/* This file was generated by SableCC (http://www.sablecc.org/). */

package cmu.node;

import cmu.analysis.Analysis;

@SuppressWarnings("nls")
public final class ADisjuncaoExp extends PExp
{
    private PExpDisjuncao _expDisjuncao_;

    public ADisjuncaoExp()
    {
        // Constructor
    }

    public ADisjuncaoExp(
        @SuppressWarnings("hiding") PExpDisjuncao _expDisjuncao_)
    {
        // Constructor
        setExpDisjuncao(_expDisjuncao_);

    }

    @Override
    public Object clone()
    {
        return new ADisjuncaoExp(
            cloneNode(this._expDisjuncao_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseADisjuncaoExp(this);
    }

    public PExpDisjuncao getExpDisjuncao()
    {
        return this._expDisjuncao_;
    }

    public void setExpDisjuncao(PExpDisjuncao node)
    {
        if(this._expDisjuncao_ != null)
        {
            this._expDisjuncao_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expDisjuncao_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._expDisjuncao_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._expDisjuncao_ == child)
        {
            this._expDisjuncao_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._expDisjuncao_ == oldChild)
        {
            setExpDisjuncao((PExpDisjuncao) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
