/* This file was generated by SableCC (http://www.sablecc.org/). */

package cmu.node;

import cmu.analysis.Analysis;

@SuppressWarnings("nls")
public final class ADuploDecConstantes extends PDecConstantes
{
    private PDecConstante _d1_;
    private TEConn _eConn_;
    private PDecConstante _d2_;

    public ADuploDecConstantes()
    {
        // Constructor
    }

    public ADuploDecConstantes(
        @SuppressWarnings("hiding") PDecConstante _d1_,
        @SuppressWarnings("hiding") TEConn _eConn_,
        @SuppressWarnings("hiding") PDecConstante _d2_)
    {
        // Constructor
        setD1(_d1_);

        setEConn(_eConn_);

        setD2(_d2_);

    }

    @Override
    public Object clone()
    {
        return new ADuploDecConstantes(
            cloneNode(this._d1_),
            cloneNode(this._eConn_),
            cloneNode(this._d2_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseADuploDecConstantes(this);
    }

    public PDecConstante getD1()
    {
        return this._d1_;
    }

    public void setD1(PDecConstante node)
    {
        if(this._d1_ != null)
        {
            this._d1_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._d1_ = node;
    }

    public TEConn getEConn()
    {
        return this._eConn_;
    }

    public void setEConn(TEConn node)
    {
        if(this._eConn_ != null)
        {
            this._eConn_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._eConn_ = node;
    }

    public PDecConstante getD2()
    {
        return this._d2_;
    }

    public void setD2(PDecConstante node)
    {
        if(this._d2_ != null)
        {
            this._d2_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._d2_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._d1_)
            + toString(this._eConn_)
            + toString(this._d2_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._d1_ == child)
        {
            this._d1_ = null;
            return;
        }

        if(this._eConn_ == child)
        {
            this._eConn_ = null;
            return;
        }

        if(this._d2_ == child)
        {
            this._d2_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._d1_ == oldChild)
        {
            setD1((PDecConstante) newChild);
            return;
        }

        if(this._eConn_ == oldChild)
        {
            setEConn((TEConn) newChild);
            return;
        }

        if(this._d2_ == oldChild)
        {
            setD2((PDecConstante) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
