/* This file was generated by SableCC (http://www.sablecc.org/). */

package cmu.node;

import cmu.analysis.Analysis;

@SuppressWarnings("nls")
public final class ANadaTipo extends PTipo
{
    private TTipoNada _tipoNada_;

    public ANadaTipo()
    {
        // Constructor
    }

    public ANadaTipo(
        @SuppressWarnings("hiding") TTipoNada _tipoNada_)
    {
        // Constructor
        setTipoNada(_tipoNada_);

    }

    @Override
    public Object clone()
    {
        return new ANadaTipo(
            cloneNode(this._tipoNada_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseANadaTipo(this);
    }

    public TTipoNada getTipoNada()
    {
        return this._tipoNada_;
    }

    public void setTipoNada(TTipoNada node)
    {
        if(this._tipoNada_ != null)
        {
            this._tipoNada_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._tipoNada_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._tipoNada_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._tipoNada_ == child)
        {
            this._tipoNada_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._tipoNada_ == oldChild)
        {
            setTipoNada((TTipoNada) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
