/* This file was generated by SableCC (http://www.sablecc.org/). */

package cmu.node;

import cmu.analysis.Analysis;

@SuppressWarnings("nls")
public final class ANumeroTipo extends PTipo
{
    private TTipoNum _tipoNum_;

    public ANumeroTipo()
    {
        // Constructor
    }

    public ANumeroTipo(
        @SuppressWarnings("hiding") TTipoNum _tipoNum_)
    {
        // Constructor
        setTipoNum(_tipoNum_);

    }

    @Override
    public Object clone()
    {
        return new ANumeroTipo(
            cloneNode(this._tipoNum_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseANumeroTipo(this);
    }

    public TTipoNum getTipoNum()
    {
        return this._tipoNum_;
    }

    public void setTipoNum(TTipoNum node)
    {
        if(this._tipoNum_ != null)
        {
            this._tipoNum_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._tipoNum_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._tipoNum_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._tipoNum_ == child)
        {
            this._tipoNum_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._tipoNum_ == oldChild)
        {
            setTipoNum((TTipoNum) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
