/* This file was generated by SableCC (http://www.sablecc.org/). */

package cmu.node;

import cmu.analysis.Analysis;

@SuppressWarnings("nls")
public final class AOuExpDisjuncao extends PExpDisjuncao
{
    private PExpDisjuncao _expDisjuncao_;
    private TOu _ou_;
    private PExpConjuncao _expConjuncao_;

    public AOuExpDisjuncao()
    {
        // Constructor
    }

    public AOuExpDisjuncao(
        @SuppressWarnings("hiding") PExpDisjuncao _expDisjuncao_,
        @SuppressWarnings("hiding") TOu _ou_,
        @SuppressWarnings("hiding") PExpConjuncao _expConjuncao_)
    {
        // Constructor
        setExpDisjuncao(_expDisjuncao_);

        setOu(_ou_);

        setExpConjuncao(_expConjuncao_);

    }

    @Override
    public Object clone()
    {
        return new AOuExpDisjuncao(
            cloneNode(this._expDisjuncao_),
            cloneNode(this._ou_),
            cloneNode(this._expConjuncao_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAOuExpDisjuncao(this);
    }

    public PExpDisjuncao getExpDisjuncao()
    {
        return this._expDisjuncao_;
    }

    public void setExpDisjuncao(PExpDisjuncao node)
    {
        if(this._expDisjuncao_ != null)
        {
            this._expDisjuncao_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expDisjuncao_ = node;
    }

    public TOu getOu()
    {
        return this._ou_;
    }

    public void setOu(TOu node)
    {
        if(this._ou_ != null)
        {
            this._ou_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._ou_ = node;
    }

    public PExpConjuncao getExpConjuncao()
    {
        return this._expConjuncao_;
    }

    public void setExpConjuncao(PExpConjuncao node)
    {
        if(this._expConjuncao_ != null)
        {
            this._expConjuncao_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expConjuncao_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._expDisjuncao_)
            + toString(this._ou_)
            + toString(this._expConjuncao_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._expDisjuncao_ == child)
        {
            this._expDisjuncao_ = null;
            return;
        }

        if(this._ou_ == child)
        {
            this._ou_ = null;
            return;
        }

        if(this._expConjuncao_ == child)
        {
            this._expConjuncao_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._expDisjuncao_ == oldChild)
        {
            setExpDisjuncao((PExpDisjuncao) newChild);
            return;
        }

        if(this._ou_ == oldChild)
        {
            setOu((TOu) newChild);
            return;
        }

        if(this._expConjuncao_ == oldChild)
        {
            setExpConjuncao((PExpConjuncao) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
