/* This file was generated by SableCC (http://www.sablecc.org/). */

package cmu.node;

import cmu.analysis.Analysis;

@SuppressWarnings("nls")
public final class ASecaoConstantes extends PSecaoConstantes
{
    private PDecConstantes _decConstantes_;

    public ASecaoConstantes()
    {
        // Constructor
    }

    public ASecaoConstantes(
        @SuppressWarnings("hiding") PDecConstantes _decConstantes_)
    {
        // Constructor
        setDecConstantes(_decConstantes_);

    }

    @Override
    public Object clone()
    {
        return new ASecaoConstantes(
            cloneNode(this._decConstantes_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASecaoConstantes(this);
    }

    public PDecConstantes getDecConstantes()
    {
        return this._decConstantes_;
    }

    public void setDecConstantes(PDecConstantes node)
    {
        if(this._decConstantes_ != null)
        {
            this._decConstantes_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._decConstantes_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._decConstantes_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._decConstantes_ == child)
        {
            this._decConstantes_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._decConstantes_ == oldChild)
        {
            setDecConstantes((PDecConstantes) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
