/* This file was generated by SableCC (http://www.sablecc.org/). */

package cmu.node;

import cmu.analysis.Analysis;

@SuppressWarnings("nls")
public final class ASeTernario extends PSeTernario
{
    private TSe _se_;
    private TEsqPar _esqPar_;
    private PExp _cond_;
    private TDirPar _dirPar_;
    private TEntao _entao_;
    private PExp _verd_;
    private TSenao _senao_;
    private PExp _falso_;

    public ASeTernario()
    {
        // Constructor
    }

    public ASeTernario(
        @SuppressWarnings("hiding") TSe _se_,
        @SuppressWarnings("hiding") TEsqPar _esqPar_,
        @SuppressWarnings("hiding") PExp _cond_,
        @SuppressWarnings("hiding") TDirPar _dirPar_,
        @SuppressWarnings("hiding") TEntao _entao_,
        @SuppressWarnings("hiding") PExp _verd_,
        @SuppressWarnings("hiding") TSenao _senao_,
        @SuppressWarnings("hiding") PExp _falso_)
    {
        // Constructor
        setSe(_se_);

        setEsqPar(_esqPar_);

        setCond(_cond_);

        setDirPar(_dirPar_);

        setEntao(_entao_);

        setVerd(_verd_);

        setSenao(_senao_);

        setFalso(_falso_);

    }

    @Override
    public Object clone()
    {
        return new ASeTernario(
            cloneNode(this._se_),
            cloneNode(this._esqPar_),
            cloneNode(this._cond_),
            cloneNode(this._dirPar_),
            cloneNode(this._entao_),
            cloneNode(this._verd_),
            cloneNode(this._senao_),
            cloneNode(this._falso_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASeTernario(this);
    }

    public TSe getSe()
    {
        return this._se_;
    }

    public void setSe(TSe node)
    {
        if(this._se_ != null)
        {
            this._se_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._se_ = node;
    }

    public TEsqPar getEsqPar()
    {
        return this._esqPar_;
    }

    public void setEsqPar(TEsqPar node)
    {
        if(this._esqPar_ != null)
        {
            this._esqPar_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._esqPar_ = node;
    }

    public PExp getCond()
    {
        return this._cond_;
    }

    public void setCond(PExp node)
    {
        if(this._cond_ != null)
        {
            this._cond_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._cond_ = node;
    }

    public TDirPar getDirPar()
    {
        return this._dirPar_;
    }

    public void setDirPar(TDirPar node)
    {
        if(this._dirPar_ != null)
        {
            this._dirPar_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._dirPar_ = node;
    }

    public TEntao getEntao()
    {
        return this._entao_;
    }

    public void setEntao(TEntao node)
    {
        if(this._entao_ != null)
        {
            this._entao_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._entao_ = node;
    }

    public PExp getVerd()
    {
        return this._verd_;
    }

    public void setVerd(PExp node)
    {
        if(this._verd_ != null)
        {
            this._verd_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._verd_ = node;
    }

    public TSenao getSenao()
    {
        return this._senao_;
    }

    public void setSenao(TSenao node)
    {
        if(this._senao_ != null)
        {
            this._senao_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._senao_ = node;
    }

    public PExp getFalso()
    {
        return this._falso_;
    }

    public void setFalso(PExp node)
    {
        if(this._falso_ != null)
        {
            this._falso_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._falso_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._se_)
            + toString(this._esqPar_)
            + toString(this._cond_)
            + toString(this._dirPar_)
            + toString(this._entao_)
            + toString(this._verd_)
            + toString(this._senao_)
            + toString(this._falso_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._se_ == child)
        {
            this._se_ = null;
            return;
        }

        if(this._esqPar_ == child)
        {
            this._esqPar_ = null;
            return;
        }

        if(this._cond_ == child)
        {
            this._cond_ = null;
            return;
        }

        if(this._dirPar_ == child)
        {
            this._dirPar_ = null;
            return;
        }

        if(this._entao_ == child)
        {
            this._entao_ = null;
            return;
        }

        if(this._verd_ == child)
        {
            this._verd_ = null;
            return;
        }

        if(this._senao_ == child)
        {
            this._senao_ = null;
            return;
        }

        if(this._falso_ == child)
        {
            this._falso_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._se_ == oldChild)
        {
            setSe((TSe) newChild);
            return;
        }

        if(this._esqPar_ == oldChild)
        {
            setEsqPar((TEsqPar) newChild);
            return;
        }

        if(this._cond_ == oldChild)
        {
            setCond((PExp) newChild);
            return;
        }

        if(this._dirPar_ == oldChild)
        {
            setDirPar((TDirPar) newChild);
            return;
        }

        if(this._entao_ == oldChild)
        {
            setEntao((TEntao) newChild);
            return;
        }

        if(this._verd_ == oldChild)
        {
            setVerd((PExp) newChild);
            return;
        }

        if(this._senao_ == oldChild)
        {
            setSenao((TSenao) newChild);
            return;
        }

        if(this._falso_ == oldChild)
        {
            setFalso((PExp) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
