/* This file was generated by SableCC (http://www.sablecc.org/). */

package cmu.node;

import cmu.analysis.Analysis;

@SuppressWarnings("nls")
public final class ASomaExpAritmetica extends PExpAritmetica
{
    private PExpAritmetica _expAritmetica_;
    private TSoma _soma_;
    private PExpFator _expFator_;

    public ASomaExpAritmetica()
    {
        // Constructor
    }

    public ASomaExpAritmetica(
        @SuppressWarnings("hiding") PExpAritmetica _expAritmetica_,
        @SuppressWarnings("hiding") TSoma _soma_,
        @SuppressWarnings("hiding") PExpFator _expFator_)
    {
        // Constructor
        setExpAritmetica(_expAritmetica_);

        setSoma(_soma_);

        setExpFator(_expFator_);

    }

    @Override
    public Object clone()
    {
        return new ASomaExpAritmetica(
            cloneNode(this._expAritmetica_),
            cloneNode(this._soma_),
            cloneNode(this._expFator_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASomaExpAritmetica(this);
    }

    public PExpAritmetica getExpAritmetica()
    {
        return this._expAritmetica_;
    }

    public void setExpAritmetica(PExpAritmetica node)
    {
        if(this._expAritmetica_ != null)
        {
            this._expAritmetica_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expAritmetica_ = node;
    }

    public TSoma getSoma()
    {
        return this._soma_;
    }

    public void setSoma(TSoma node)
    {
        if(this._soma_ != null)
        {
            this._soma_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._soma_ = node;
    }

    public PExpFator getExpFator()
    {
        return this._expFator_;
    }

    public void setExpFator(PExpFator node)
    {
        if(this._expFator_ != null)
        {
            this._expFator_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expFator_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._expAritmetica_)
            + toString(this._soma_)
            + toString(this._expFator_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._expAritmetica_ == child)
        {
            this._expAritmetica_ = null;
            return;
        }

        if(this._soma_ == child)
        {
            this._soma_ = null;
            return;
        }

        if(this._expFator_ == child)
        {
            this._expFator_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._expAritmetica_ == oldChild)
        {
            setExpAritmetica((PExpAritmetica) newChild);
            return;
        }

        if(this._soma_ == oldChild)
        {
            setSoma((TSoma) newChild);
            return;
        }

        if(this._expFator_ == oldChild)
        {
            setExpFator((PExpFator) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
