/* This file was generated by SableCC (http://www.sablecc.org/). */

package cmu.node;

import cmu.analysis.Analysis;

@SuppressWarnings("nls")
public final class AUnicoParametrosAssinatura extends PParametrosAssinatura
{
    private PParamGeral _paramGeral_;

    public AUnicoParametrosAssinatura()
    {
        // Constructor
    }

    public AUnicoParametrosAssinatura(
        @SuppressWarnings("hiding") PParamGeral _paramGeral_)
    {
        // Constructor
        setParamGeral(_paramGeral_);

    }

    @Override
    public Object clone()
    {
        return new AUnicoParametrosAssinatura(
            cloneNode(this._paramGeral_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAUnicoParametrosAssinatura(this);
    }

    public PParamGeral getParamGeral()
    {
        return this._paramGeral_;
    }

    public void setParamGeral(PParamGeral node)
    {
        if(this._paramGeral_ != null)
        {
            this._paramGeral_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._paramGeral_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._paramGeral_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._paramGeral_ == child)
        {
            this._paramGeral_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._paramGeral_ == oldChild)
        {
            setParamGeral((PParamGeral) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
