/* This file was generated by SableCC (http://www.sablecc.org/). */

package cmu.node;

import cmu.analysis.Analysis;

@SuppressWarnings("nls")
public final class TDizSer extends Token
{
    public TDizSer()
    {
        super.setText("diz ser");
    }

    public TDizSer(int line, int pos)
    {
        super.setText("diz ser");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TDizSer(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTDizSer(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TDizSer text.");
    }
}
