/* This file was generated by SableCC (http://www.sablecc.org/). */

package cmu.node;

import cmu.analysis.Analysis;

@SuppressWarnings("nls")
public final class TElaIraTeRetornar extends Token
{
    public TElaIraTeRetornar()
    {
        super.setText("ela ira te retornar");
    }

    public TElaIraTeRetornar(int line, int pos)
    {
        super.setText("ela ira te retornar");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TElaIraTeRetornar(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTElaIraTeRetornar(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TElaIraTeRetornar text.");
    }
}
