/* This file was generated by SableCC (http://www.sablecc.org/). */

package cmu.node;

import cmu.analysis.Analysis;

@SuppressWarnings("nls")
public final class TIa extends Token
{
    public TIa()
    {
        super.setText("ia");
    }

    public TIa(int line, int pos)
    {
        super.setText("ia");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TIa(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTIa(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TIa text.");
    }
}
