/* This file was generated by SableCC (http://www.sablecc.org/). */

package cmu.node;

import cmu.analysis.Analysis;

@SuppressWarnings("nls")
public final class TParaVoceArranjar extends Token
{
    public TParaVoceArranjar()
    {
        super.setText("para voce arranjar");
    }

    public TParaVoceArranjar(int line, int pos)
    {
        super.setText("para voce arranjar");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TParaVoceArranjar(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTParaVoceArranjar(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TParaVoceArranjar text.");
    }
}
