/* This file was generated by SableCC (http://www.sablecc.org/). */

package cmu.node;

import cmu.analysis.Analysis;

@SuppressWarnings("nls")
public final class TSeCond extends Token
{
    public TSeCond()
    {
        super.setText("Se");
    }

    public TSeCond(int line, int pos)
    {
        super.setText("Se");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TSeCond(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTSeCond(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TSeCond text.");
    }
}
