/* This file was generated by SableCC (http://www.sablecc.org/). */

package cmu.node;

import cmu.analysis.Analysis;

@SuppressWarnings("nls")
public final class TUmaCondicaoAssim extends Token
{
    public TUmaCondicaoAssim()
    {
        super.setText("uma condicao assim:");
    }

    public TUmaCondicaoAssim(int line, int pos)
    {
        super.setText("uma condicao assim:");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TUmaCondicaoAssim(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTUmaCondicaoAssim(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TUmaCondicaoAssim text.");
    }
}
