/* This file was generated by SableCC (http://www.sablecc.org/). */

package cordelmaisum.node;

import cordelmaisum.analysis.*;

@SuppressWarnings("nls")
public final class TAqui extends Token
{
    public TAqui()
    {
        super.setText("aqui");
    }

    public TAqui(int line, int pos)
    {
        super.setText("aqui");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TAqui(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTAqui(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TAqui text.");
    }
}
