/* This file was generated by SableCC (http://www.sablecc.org/). */

package cordelmaisum.node;

import cordelmaisum.analysis.*;

@SuppressWarnings("nls")
public final class TCom extends Token
{
    public TCom()
    {
        super.setText("Com");
    }

    public TCom(int line, int pos)
    {
        super.setText("Com");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TCom(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTCom(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TCom text.");
    }
}
