/* This file was generated by SableCC (http://www.sablecc.org/). */

package cordelmaisum.node;

import cordelmaisum.analysis.*;

@SuppressWarnings("nls")
public final class TO extends Token
{
    public TO()
    {
        super.setText("o");
    }

    public TO(int line, int pos)
    {
        super.setText("o");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TO(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTO(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TO text.");
    }
}
