/* This file was generated by SableCC (http://www.sablecc.org/). */

package cordelmaisum.node;

import cordelmaisum.analysis.*;

@SuppressWarnings("nls")
public final class TTe extends Token
{
    public TTe()
    {
        super.setText("te");
    }

    public TTe(int line, int pos)
    {
        super.setText("te");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TTe(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTTe(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TTe text.");
    }
}
