/* This file was generated by SableCC (http://www.sablecc.org/). */

package cordelmaisum.analysis;

import cordelmaisum.node.*;

import java.util.Hashtable;

public class AnalysisAdapter implements Analysis
{
    private Hashtable<Node,Object> in;
    private Hashtable<Node,Object> out;

    @Override
    public Object getIn(Node node)
    {
        if(this.in == null)
        {
            return null;
        }

        return this.in.get(node);
    }

    @Override
    public void setIn(Node node, Object o)
    {
        if(this.in == null)
        {
            this.in = new Hashtable<Node,Object>(1);
        }

        if(o != null)
        {
            this.in.put(node, o);
        }
        else
        {
            this.in.remove(node);
        }
    }

    @Override
    public Object getOut(Node node)
    {
        if(this.out == null)
        {
            return null;
        }

        return this.out.get(node);
    }

    @Override
    public void setOut(Node node, Object o)
    {
        if(this.out == null)
        {
            this.out = new Hashtable<Node,Object>(1);
        }

        if(o != null)
        {
            this.out.put(node, o);
        }
        else
        {
            this.out.remove(node);
        }
    }

    @Override
    public void caseStart(Start node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAPrograma(APrograma node)
    {
        defaultCase(node);
    }

    @Override
    public void caseADecFuncao(ADecFuncao node)
    {
        defaultCase(node);
    }

    @Override
    public void caseANumeroTipo(ANumeroTipo node)
    {
        defaultCase(node);
    }

    @Override
    public void caseARespostaTipo(ARespostaTipo node)
    {
        defaultCase(node);
    }

    @Override
    public void caseANadaTipo(ANadaTipo node)
    {
        defaultCase(node);
    }

    @Override
    public void caseADeclaracaoParamGeral(ADeclaracaoParamGeral node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAAssinaturaParamGeral(AAssinaturaParamGeral node)
    {
        defaultCase(node);
    }

    @Override
    public void caseATernarioExp(ATernarioExp node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAOuExp(AOuExp node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAEExp(AEExp node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAIgualExp(AIgualExp node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAMaiorExp(AMaiorExp node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAMenorExp(AMenorExp node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAMaiorIgualExp(AMaiorIgualExp node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAMenorIgualExp(AMenorIgualExp node)
    {
        defaultCase(node);
    }

    @Override
    public void caseASomaExp(ASomaExp node)
    {
        defaultCase(node);
    }

    @Override
    public void caseASubExp(ASubExp node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAMultExp(AMultExp node)
    {
        defaultCase(node);
    }

    @Override
    public void caseADivExp(ADivExp node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAModExp(AModExp node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAMenosExp(AMenosExp node)
    {
        defaultCase(node);
    }

    @Override
    public void caseANaoExp(ANaoExp node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAIntExp(AIntExp node)
    {
        defaultCase(node);
    }

    @Override
    public void caseARealExp(ARealExp node)
    {
        defaultCase(node);
    }

    @Override
    public void caseASimExp(ASimExp node)
    {
        defaultCase(node);
    }

    @Override
    public void caseANaoValExp(ANaoValExp node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAIdExp(AIdExp node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAChamadaExp(AChamadaExp node)
    {
        defaultCase(node);
    }

    @Override
    public void caseABoolExp(ABoolExp node)
    {
        defaultCase(node);
    }

    @Override
    public void caseASimBoolVal(ASimBoolVal node)
    {
        defaultCase(node);
    }

    @Override
    public void caseANaoBoolVal(ANaoBoolVal node)
    {
        defaultCase(node);
    }

    @Override
    public void caseADecConstante(ADecConstante node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTJa(TJa node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTIa(TIa node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTEsquecendo(TEsquecendo node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTTresPontos(TTresPontos node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTPreste(TPreste node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTAtencao(TAtencao node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTPor(TPor node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTFavor(TFavor node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTDizSer(TDizSer node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTDiz(TDiz node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTSer(TSer node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTQueTem(TQueTem node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTComoValor(TComoValor node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTEConn(TEConn node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTCom(TCom node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTAFuncao(TAFuncao node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTArruma(TArruma node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTPonto(TPonto node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTVirgula(TVirgula node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTSeCond(TSeCond node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTParaEla(TParaEla node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTParaVoceArranjar(TParaVoceArranjar node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTVoceArranjar(TVoceArranjar node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTOValorDe(TOValorDe node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTOResultadoDe(TOResultadoDe node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTElaIraTeRetornar(TElaIraTeRetornar node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTIra(TIra node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTRetornar(TRetornar node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTTe(TTe node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTMarcadorInicio(TMarcadorInicio node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTSua(TSua node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTLicenca(TLicenca node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTAqui(TAqui node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTVamos(TVamos node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTComecar(TComecar node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTExclamacao(TExclamacao node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTTipoNum(TTipoNum node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTTipoBool(TTipoBool node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTTipoNada(TTipoNada node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTNumero(TNumero node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTResposta(TResposta node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTNada(TNada node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTSe(TSe node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTEntao(TEntao node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTSenao(TSenao node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTUmaFuncao(TUmaFuncao node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTFuncao(TFuncao node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTQueArruma(TQueArruma node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTQue(TQue node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTEmTrocaDe(TEmTrocaDe node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTEm(TEm node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTTroca(TTroca node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTEla(TEla node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTDe(TDe node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTSim(TSim node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTNao(TNao node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTTem(TTem node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTValor(TValor node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTPara(TPara node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTVoce(TVoce node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTArranjar(TArranjar node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTComo(TComo node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTO(TO node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTResultado(TResultado node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTSoma(TSoma node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTSub(TSub node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTMult(TMult node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTDiv(TDiv node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTMod(TMod node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTMaiorIgual(TMaiorIgual node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTMenorIgual(TMenorIgual node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTMaior(TMaior node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTMenor(TMenor node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTIgual(TIgual node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTOu(TOu node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTEsqPar(TEsqPar node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTDirPar(TDirPar node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTEsqCol(TEsqCol node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTDirCol(TDirCol node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTBarra(TBarra node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTDoisPontos(TDoisPontos node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTPontoVirgula(TPontoVirgula node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTUmaCondicaoAssim(TUmaCondicaoAssim node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTUma(TUma node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTUm(TUm node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTCondicao(TCondicao node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTAssim(TAssim node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTId(TId node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTNumInt(TNumInt node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTNumReal(TNumReal node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTComentarioLinha(TComentarioLinha node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTComentarioBloco(TComentarioBloco node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTBranco(TBranco node)
    {
        defaultCase(node);
    }

    @Override
    public void caseEOF(EOF node)
    {
        defaultCase(node);
    }

    @Override
    public void caseInvalidToken(InvalidToken node)
    {
        defaultCase(node);
    }

    public void defaultCase(@SuppressWarnings("unused") Node node)
    {
        // do nothing
    }
}
