/* This file was generated by SableCC (http://www.sablecc.org/). */

package cordelmaisum.analysis;

import java.util.*;
import cordelmaisum.node.*;

public class AnalysisAdapter implements Analysis
{
    private Hashtable<Node,Object> in;
    private Hashtable<Node,Object> out;

    @Override
    public Object getIn(Node node)
    {
        if(this.in == null)
        {
            return null;
        }

        return this.in.get(node);
    }

    @Override
    public void setIn(Node node, Object o)
    {
        if(this.in == null)
        {
            this.in = new Hashtable<Node,Object>(1);
        }

        if(o != null)
        {
            this.in.put(node, o);
        }
        else
        {
            this.in.remove(node);
        }
    }

    @Override
    public Object getOut(Node node)
    {
        if(this.out == null)
        {
            return null;
        }

        return this.out.get(node);
    }

    @Override
    public void setOut(Node node, Object o)
    {
        if(this.out == null)
        {
            this.out = new Hashtable<Node,Object>(1);
        }

        if(o != null)
        {
            this.out.put(node, o);
        }
        else
        {
            this.out.remove(node);
        }
    }

    @Override
    public void caseTCom(TCom node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTSua(TSua node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTLicenca(TLicenca node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTVirgula(TVirgula node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTPor(TPor node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTAqui(TAqui node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTVamos(TVamos node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTComecar(TComecar node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTExclamacao(TExclamacao node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTSeCondicional(TSeCondicional node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTSe(TSe node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTSenao(TSenao node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTEntao(TEntao node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTUma(TUma node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTCondicao(TCondicao node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTAssim(TAssim node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTJa(TJa node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTIa(TIa node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTEsquecendo(TEsquecendo node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTPonto(TPonto node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTTresPontos(TTresPontos node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTPreste(TPreste node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTAtencao(TAtencao node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTFavor(TFavor node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTDoisPontos(TDoisPontos node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTDiz(TDiz node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTSer(TSer node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTQue(TQue node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTTem(TTem node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTComo(TComo node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTValor(TValor node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTUm(TUm node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTFuncao(TFuncao node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTArruma(TArruma node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTEm(TEm node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTTroca(TTroca node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTDe(TDe node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTAGrande(TAGrande node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTPara(TPara node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTEla(TEla node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTVoce(TVoce node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTArranjar(TArranjar node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTO(TO node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTIra(TIra node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTTe(TTe node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTRetornar(TRetornar node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTResposta(TResposta node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTOperadorAritmetico(TOperadorAritmetico node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTSeparador(TSeparador node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTOperadorRelacional(TOperadorRelacional node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTOperadorBooleano(TOperadorBooleano node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTNumeroReal(TNumeroReal node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTNumeroInteiro(TNumeroInteiro node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTTipo(TTipo node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTParEsq(TParEsq node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTParDir(TParDir node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTColchEsq(TColchEsq node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTColchDir(TColchDir node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTId(TId node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTCommentsBloco(TCommentsBloco node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTCommentsLinha(TCommentsLinha node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTVazio(TVazio node)
    {
        defaultCase(node);
    }

    @Override
    public void caseEOF(EOF node)
    {
        defaultCase(node);
    }

    @Override
    public void caseInvalidToken(InvalidToken node)
    {
        defaultCase(node);
    }

    public void defaultCase(@SuppressWarnings("unused") Node node)
    {
        // do nothing
    }
}
