/* This file was generated by SableCC (http://www.sablecc.org/). */

package cordelmaisum.analysis;

import cordelmaisum.node.*;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

public class ReversedDepthFirstAdapter extends AnalysisAdapter
{
    public void inStart(Start node)
    {
        defaultIn(node);
    }

    public void outStart(Start node)
    {
        defaultOut(node);
    }

    public void defaultIn(@SuppressWarnings("unused") Node node)
    {
        // Do nothing
    }

    public void defaultOut(@SuppressWarnings("unused") Node node)
    {
        // Do nothing
    }

    @Override
    public void caseStart(Start node)
    {
        inStart(node);
        node.getEOF().apply(this);
        node.getPPrograma().apply(this);
        outStart(node);
    }

    public void inAPrograma(APrograma node)
    {
        defaultIn(node);
    }

    public void outAPrograma(APrograma node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAPrograma(APrograma node)
    {
        inAPrograma(node);
        {
            List<PDecFuncao> copy = new ArrayList<PDecFuncao>(node.getDecFuncao());
            Collections.reverse(copy);
            for(PDecFuncao e : copy)
            {
                e.apply(this);
            }
        }
        outAPrograma(node);
    }

    public void inADecFuncao(ADecFuncao node)
    {
        defaultIn(node);
    }

    public void outADecFuncao(ADecFuncao node)
    {
        defaultOut(node);
    }

    @Override
    public void caseADecFuncao(ADecFuncao node)
    {
        inADecFuncao(node);
        {
            List<PDecConstante> copy = new ArrayList<PDecConstante>(node.getConstantes());
            Collections.reverse(copy);
            for(PDecConstante e : copy)
            {
                e.apply(this);
            }
        }
        if(node.getRetorno() != null)
        {
            node.getRetorno().apply(this);
        }
        {
            List<PParamGeral> copy = new ArrayList<PParamGeral>(node.getParams());
            Collections.reverse(copy);
            for(PParamGeral e : copy)
            {
                e.apply(this);
            }
        }
        if(node.getTipoRetorno() != null)
        {
            node.getTipoRetorno().apply(this);
        }
        if(node.getNome() != null)
        {
            node.getNome().apply(this);
        }
        if(node.getMarcador() != null)
        {
            node.getMarcador().apply(this);
        }
        outADecFuncao(node);
    }

    public void inANumeroTipo(ANumeroTipo node)
    {
        defaultIn(node);
    }

    public void outANumeroTipo(ANumeroTipo node)
    {
        defaultOut(node);
    }

    @Override
    public void caseANumeroTipo(ANumeroTipo node)
    {
        inANumeroTipo(node);
        outANumeroTipo(node);
    }

    public void inARespostaTipo(ARespostaTipo node)
    {
        defaultIn(node);
    }

    public void outARespostaTipo(ARespostaTipo node)
    {
        defaultOut(node);
    }

    @Override
    public void caseARespostaTipo(ARespostaTipo node)
    {
        inARespostaTipo(node);
        outARespostaTipo(node);
    }

    public void inANadaTipo(ANadaTipo node)
    {
        defaultIn(node);
    }

    public void outANadaTipo(ANadaTipo node)
    {
        defaultOut(node);
    }

    @Override
    public void caseANadaTipo(ANadaTipo node)
    {
        inANadaTipo(node);
        outANadaTipo(node);
    }

    public void inADeclaracaoParamGeral(ADeclaracaoParamGeral node)
    {
        defaultIn(node);
    }

    public void outADeclaracaoParamGeral(ADeclaracaoParamGeral node)
    {
        defaultOut(node);
    }

    @Override
    public void caseADeclaracaoParamGeral(ADeclaracaoParamGeral node)
    {
        inADeclaracaoParamGeral(node);
        if(node.getNome() != null)
        {
            node.getNome().apply(this);
        }
        if(node.getTipo() != null)
        {
            node.getTipo().apply(this);
        }
        outADeclaracaoParamGeral(node);
    }

    public void inAAssinaturaParamGeral(AAssinaturaParamGeral node)
    {
        defaultIn(node);
    }

    public void outAAssinaturaParamGeral(AAssinaturaParamGeral node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAAssinaturaParamGeral(AAssinaturaParamGeral node)
    {
        inAAssinaturaParamGeral(node);
        {
            List<PParamGeral> copy = new ArrayList<PParamGeral>(node.getParams());
            Collections.reverse(copy);
            for(PParamGeral e : copy)
            {
                e.apply(this);
            }
        }
        if(node.getTipoRetorno() != null)
        {
            node.getTipoRetorno().apply(this);
        }
        if(node.getNome() != null)
        {
            node.getNome().apply(this);
        }
        outAAssinaturaParamGeral(node);
    }

    public void inATernarioExp(ATernarioExp node)
    {
        defaultIn(node);
    }

    public void outATernarioExp(ATernarioExp node)
    {
        defaultOut(node);
    }

    @Override
    public void caseATernarioExp(ATernarioExp node)
    {
        inATernarioExp(node);
        if(node.getFalso() != null)
        {
            node.getFalso().apply(this);
        }
        if(node.getVerd() != null)
        {
            node.getVerd().apply(this);
        }
        if(node.getCond() != null)
        {
            node.getCond().apply(this);
        }
        outATernarioExp(node);
    }

    public void inAOuExp(AOuExp node)
    {
        defaultIn(node);
    }

    public void outAOuExp(AOuExp node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAOuExp(AOuExp node)
    {
        inAOuExp(node);
        if(node.getDir() != null)
        {
            node.getDir().apply(this);
        }
        if(node.getEsq() != null)
        {
            node.getEsq().apply(this);
        }
        outAOuExp(node);
    }

    public void inAEExp(AEExp node)
    {
        defaultIn(node);
    }

    public void outAEExp(AEExp node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAEExp(AEExp node)
    {
        inAEExp(node);
        if(node.getDir() != null)
        {
            node.getDir().apply(this);
        }
        if(node.getEsq() != null)
        {
            node.getEsq().apply(this);
        }
        outAEExp(node);
    }

    public void inAIgualExp(AIgualExp node)
    {
        defaultIn(node);
    }

    public void outAIgualExp(AIgualExp node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAIgualExp(AIgualExp node)
    {
        inAIgualExp(node);
        if(node.getDir() != null)
        {
            node.getDir().apply(this);
        }
        if(node.getEsq() != null)
        {
            node.getEsq().apply(this);
        }
        outAIgualExp(node);
    }

    public void inAMaiorExp(AMaiorExp node)
    {
        defaultIn(node);
    }

    public void outAMaiorExp(AMaiorExp node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAMaiorExp(AMaiorExp node)
    {
        inAMaiorExp(node);
        if(node.getDir() != null)
        {
            node.getDir().apply(this);
        }
        if(node.getEsq() != null)
        {
            node.getEsq().apply(this);
        }
        outAMaiorExp(node);
    }

    public void inAMenorExp(AMenorExp node)
    {
        defaultIn(node);
    }

    public void outAMenorExp(AMenorExp node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAMenorExp(AMenorExp node)
    {
        inAMenorExp(node);
        if(node.getDir() != null)
        {
            node.getDir().apply(this);
        }
        if(node.getEsq() != null)
        {
            node.getEsq().apply(this);
        }
        outAMenorExp(node);
    }

    public void inAMaiorIgualExp(AMaiorIgualExp node)
    {
        defaultIn(node);
    }

    public void outAMaiorIgualExp(AMaiorIgualExp node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAMaiorIgualExp(AMaiorIgualExp node)
    {
        inAMaiorIgualExp(node);
        if(node.getDir() != null)
        {
            node.getDir().apply(this);
        }
        if(node.getEsq() != null)
        {
            node.getEsq().apply(this);
        }
        outAMaiorIgualExp(node);
    }

    public void inAMenorIgualExp(AMenorIgualExp node)
    {
        defaultIn(node);
    }

    public void outAMenorIgualExp(AMenorIgualExp node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAMenorIgualExp(AMenorIgualExp node)
    {
        inAMenorIgualExp(node);
        if(node.getDir() != null)
        {
            node.getDir().apply(this);
        }
        if(node.getEsq() != null)
        {
            node.getEsq().apply(this);
        }
        outAMenorIgualExp(node);
    }

    public void inASomaExp(ASomaExp node)
    {
        defaultIn(node);
    }

    public void outASomaExp(ASomaExp node)
    {
        defaultOut(node);
    }

    @Override
    public void caseASomaExp(ASomaExp node)
    {
        inASomaExp(node);
        if(node.getDir() != null)
        {
            node.getDir().apply(this);
        }
        if(node.getEsq() != null)
        {
            node.getEsq().apply(this);
        }
        outASomaExp(node);
    }

    public void inASubExp(ASubExp node)
    {
        defaultIn(node);
    }

    public void outASubExp(ASubExp node)
    {
        defaultOut(node);
    }

    @Override
    public void caseASubExp(ASubExp node)
    {
        inASubExp(node);
        if(node.getDir() != null)
        {
            node.getDir().apply(this);
        }
        if(node.getEsq() != null)
        {
            node.getEsq().apply(this);
        }
        outASubExp(node);
    }

    public void inAMultExp(AMultExp node)
    {
        defaultIn(node);
    }

    public void outAMultExp(AMultExp node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAMultExp(AMultExp node)
    {
        inAMultExp(node);
        if(node.getDir() != null)
        {
            node.getDir().apply(this);
        }
        if(node.getEsq() != null)
        {
            node.getEsq().apply(this);
        }
        outAMultExp(node);
    }

    public void inADivExp(ADivExp node)
    {
        defaultIn(node);
    }

    public void outADivExp(ADivExp node)
    {
        defaultOut(node);
    }

    @Override
    public void caseADivExp(ADivExp node)
    {
        inADivExp(node);
        if(node.getDir() != null)
        {
            node.getDir().apply(this);
        }
        if(node.getEsq() != null)
        {
            node.getEsq().apply(this);
        }
        outADivExp(node);
    }

    public void inAModExp(AModExp node)
    {
        defaultIn(node);
    }

    public void outAModExp(AModExp node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAModExp(AModExp node)
    {
        inAModExp(node);
        if(node.getDir() != null)
        {
            node.getDir().apply(this);
        }
        if(node.getEsq() != null)
        {
            node.getEsq().apply(this);
        }
        outAModExp(node);
    }

    public void inAMenosExp(AMenosExp node)
    {
        defaultIn(node);
    }

    public void outAMenosExp(AMenosExp node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAMenosExp(AMenosExp node)
    {
        inAMenosExp(node);
        if(node.getExp() != null)
        {
            node.getExp().apply(this);
        }
        outAMenosExp(node);
    }

    public void inANaoExp(ANaoExp node)
    {
        defaultIn(node);
    }

    public void outANaoExp(ANaoExp node)
    {
        defaultOut(node);
    }

    @Override
    public void caseANaoExp(ANaoExp node)
    {
        inANaoExp(node);
        if(node.getExp() != null)
        {
            node.getExp().apply(this);
        }
        outANaoExp(node);
    }

    public void inAIntExp(AIntExp node)
    {
        defaultIn(node);
    }

    public void outAIntExp(AIntExp node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAIntExp(AIntExp node)
    {
        inAIntExp(node);
        if(node.getNumInt() != null)
        {
            node.getNumInt().apply(this);
        }
        outAIntExp(node);
    }

    public void inARealExp(ARealExp node)
    {
        defaultIn(node);
    }

    public void outARealExp(ARealExp node)
    {
        defaultOut(node);
    }

    @Override
    public void caseARealExp(ARealExp node)
    {
        inARealExp(node);
        if(node.getNumReal() != null)
        {
            node.getNumReal().apply(this);
        }
        outARealExp(node);
    }

    public void inASimExp(ASimExp node)
    {
        defaultIn(node);
    }

    public void outASimExp(ASimExp node)
    {
        defaultOut(node);
    }

    @Override
    public void caseASimExp(ASimExp node)
    {
        inASimExp(node);
        outASimExp(node);
    }

    public void inANaoValExp(ANaoValExp node)
    {
        defaultIn(node);
    }

    public void outANaoValExp(ANaoValExp node)
    {
        defaultOut(node);
    }

    @Override
    public void caseANaoValExp(ANaoValExp node)
    {
        inANaoValExp(node);
        outANaoValExp(node);
    }

    public void inAIdExp(AIdExp node)
    {
        defaultIn(node);
    }

    public void outAIdExp(AIdExp node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAIdExp(AIdExp node)
    {
        inAIdExp(node);
        if(node.getId() != null)
        {
            node.getId().apply(this);
        }
        outAIdExp(node);
    }

    public void inAChamadaExp(AChamadaExp node)
    {
        defaultIn(node);
    }

    public void outAChamadaExp(AChamadaExp node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAChamadaExp(AChamadaExp node)
    {
        inAChamadaExp(node);
        {
            List<PExp> copy = new ArrayList<PExp>(node.getArgs());
            Collections.reverse(copy);
            for(PExp e : copy)
            {
                e.apply(this);
            }
        }
        if(node.getNome() != null)
        {
            node.getNome().apply(this);
        }
        outAChamadaExp(node);
    }

    public void inABoolExp(ABoolExp node)
    {
        defaultIn(node);
    }

    public void outABoolExp(ABoolExp node)
    {
        defaultOut(node);
    }

    @Override
    public void caseABoolExp(ABoolExp node)
    {
        inABoolExp(node);
        if(node.getBoolVal() != null)
        {
            node.getBoolVal().apply(this);
        }
        outABoolExp(node);
    }

    public void inASimBoolVal(ASimBoolVal node)
    {
        defaultIn(node);
    }

    public void outASimBoolVal(ASimBoolVal node)
    {
        defaultOut(node);
    }

    @Override
    public void caseASimBoolVal(ASimBoolVal node)
    {
        inASimBoolVal(node);
        outASimBoolVal(node);
    }

    public void inANaoBoolVal(ANaoBoolVal node)
    {
        defaultIn(node);
    }

    public void outANaoBoolVal(ANaoBoolVal node)
    {
        defaultOut(node);
    }

    @Override
    public void caseANaoBoolVal(ANaoBoolVal node)
    {
        inANaoBoolVal(node);
        outANaoBoolVal(node);
    }

    public void inADecConstante(ADecConstante node)
    {
        defaultIn(node);
    }

    public void outADecConstante(ADecConstante node)
    {
        defaultOut(node);
    }

    @Override
    public void caseADecConstante(ADecConstante node)
    {
        inADecConstante(node);
        if(node.getValor() != null)
        {
            node.getValor().apply(this);
        }
        if(node.getTipo() != null)
        {
            node.getTipo().apply(this);
        }
        if(node.getNome() != null)
        {
            node.getNome().apply(this);
        }
        outADecConstante(node);
    }
}
