/* This file was generated by SableCC (http://www.sablecc.org/). */

package cordelmaisum.node;

import cordelmaisum.analysis.Analysis;

import java.util.LinkedList;
import java.util.List;
import java.util.ListIterator;

@SuppressWarnings("nls")
public final class ADecFuncao extends PDecFuncao
{
    private TMarcadorInicio _marcador_;
    private TId _nome_;
    private PTipo _tipoRetorno_;
    private final LinkedList<PParamGeral> _params_ = new LinkedList<PParamGeral>();
    private PExp _retorno_;
    private final LinkedList<PDecConstante> _constantes_ = new LinkedList<PDecConstante>();

    public ADecFuncao()
    {
        // Constructor
    }

    public ADecFuncao(
        @SuppressWarnings("hiding") TMarcadorInicio _marcador_,
        @SuppressWarnings("hiding") TId _nome_,
        @SuppressWarnings("hiding") PTipo _tipoRetorno_,
        @SuppressWarnings("hiding") List<?> _params_,
        @SuppressWarnings("hiding") PExp _retorno_,
        @SuppressWarnings("hiding") List<?> _constantes_)
    {
        // Constructor
        setMarcador(_marcador_);

        setNome(_nome_);

        setTipoRetorno(_tipoRetorno_);

        setParams(_params_);

        setRetorno(_retorno_);

        setConstantes(_constantes_);

    }

    @Override
    public Object clone()
    {
        return new ADecFuncao(
            cloneNode(this._marcador_),
            cloneNode(this._nome_),
            cloneNode(this._tipoRetorno_),
            cloneList(this._params_),
            cloneNode(this._retorno_),
            cloneList(this._constantes_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseADecFuncao(this);
    }

    public TMarcadorInicio getMarcador()
    {
        return this._marcador_;
    }

    public void setMarcador(TMarcadorInicio node)
    {
        if(this._marcador_ != null)
        {
            this._marcador_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._marcador_ = node;
    }

    public TId getNome()
    {
        return this._nome_;
    }

    public void setNome(TId node)
    {
        if(this._nome_ != null)
        {
            this._nome_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._nome_ = node;
    }

    public PTipo getTipoRetorno()
    {
        return this._tipoRetorno_;
    }

    public void setTipoRetorno(PTipo node)
    {
        if(this._tipoRetorno_ != null)
        {
            this._tipoRetorno_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._tipoRetorno_ = node;
    }

    public LinkedList<PParamGeral> getParams()
    {
        return this._params_;
    }

    public void setParams(List<?> list)
    {
        for(PParamGeral e : this._params_)
        {
            e.parent(null);
        }
        this._params_.clear();

        for(Object obj_e : list)
        {
            PParamGeral e = (PParamGeral) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._params_.add(e);
        }
    }

    public PExp getRetorno()
    {
        return this._retorno_;
    }

    public void setRetorno(PExp node)
    {
        if(this._retorno_ != null)
        {
            this._retorno_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._retorno_ = node;
    }

    public LinkedList<PDecConstante> getConstantes()
    {
        return this._constantes_;
    }

    public void setConstantes(List<?> list)
    {
        for(PDecConstante e : this._constantes_)
        {
            e.parent(null);
        }
        this._constantes_.clear();

        for(Object obj_e : list)
        {
            PDecConstante e = (PDecConstante) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._constantes_.add(e);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._marcador_)
            + toString(this._nome_)
            + toString(this._tipoRetorno_)
            + toString(this._params_)
            + toString(this._retorno_)
            + toString(this._constantes_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._marcador_ == child)
        {
            this._marcador_ = null;
            return;
        }

        if(this._nome_ == child)
        {
            this._nome_ = null;
            return;
        }

        if(this._tipoRetorno_ == child)
        {
            this._tipoRetorno_ = null;
            return;
        }

        if(this._params_.remove(child))
        {
            return;
        }

        if(this._retorno_ == child)
        {
            this._retorno_ = null;
            return;
        }

        if(this._constantes_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._marcador_ == oldChild)
        {
            setMarcador((TMarcadorInicio) newChild);
            return;
        }

        if(this._nome_ == oldChild)
        {
            setNome((TId) newChild);
            return;
        }

        if(this._tipoRetorno_ == oldChild)
        {
            setTipoRetorno((PTipo) newChild);
            return;
        }

        for(ListIterator<PParamGeral> i = this._params_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PParamGeral) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        if(this._retorno_ == oldChild)
        {
            setRetorno((PExp) newChild);
            return;
        }

        for(ListIterator<PDecConstante> i = this._constantes_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PDecConstante) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
