/* This file was generated by SableCC (http://www.sablecc.org/). */

package cordelmaisum.node;

import cordelmaisum.analysis.Analysis;

@SuppressWarnings("nls")
public final class ANaoBoolVal extends PBoolVal
{

    public ANaoBoolVal()
    {
        // Constructor
    }

    @Override
    public Object clone()
    {
        return new ANaoBoolVal();
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseANaoBoolVal(this);
    }

    @Override
    public String toString()
    {
        return "";
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        throw new RuntimeException("Not a child.");
    }
}
