/* This file was generated by SableCC (http://www.sablecc.org/). */

package cordelmaisum.node;

import cordelmaisum.analysis.Analysis;

@SuppressWarnings("nls")
public final class TComecar extends Token
{
    public TComecar()
    {
        super.setText("comecar");
    }

    public TComecar(int line, int pos)
    {
        super.setText("comecar");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TComecar(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTComecar(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TComecar text.");
    }
}
