/* This file was generated by SableCC (http://www.sablecc.org/). */

package cordelmaisum.node;

import cordelmaisum.analysis.*;

@SuppressWarnings("nls")
public final class TCommentsBloco extends Token
{
    public TCommentsBloco(String text)
    {
        setText(text);
    }

    public TCommentsBloco(String text, int line, int pos)
    {
        setText(text);
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TCommentsBloco(getText(), getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTCommentsBloco(this);
    }
}
