/* This file was generated by SableCC (http://www.sablecc.org/). */

package cordelmaisum.node;

import cordelmaisum.analysis.Analysis;

@SuppressWarnings("nls")
public final class TDiz extends Token
{
    public TDiz()
    {
        super.setText("diz");
    }

    public TDiz(int line, int pos)
    {
        super.setText("diz");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TDiz(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTDiz(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TDiz text.");
    }
}
