/* This file was generated by SableCC (http://www.sablecc.org/). */

package cordelmaisum.node;

import cordelmaisum.analysis.Analysis;

@SuppressWarnings("nls")
public final class TEla extends Token
{
    public TEla()
    {
        super.setText("ela");
    }

    public TEla(int line, int pos)
    {
        super.setText("ela");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TEla(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTEla(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TEla text.");
    }
}
