/* This file was generated by SableCC (http://www.sablecc.org/). */

package cordelmaisum.node;

import cordelmaisum.analysis.Analysis;

@SuppressWarnings("nls")
public final class TLicenca extends Token
{
    public TLicenca()
    {
        super.setText("licenca");
    }

    public TLicenca(int line, int pos)
    {
        super.setText("licenca");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TLicenca(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTLicenca(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TLicenca text.");
    }
}
