/* This file was generated by SableCC (http://www.sablecc.org/). */

package cordelmaisum.node;

import cordelmaisum.analysis.Analysis;

@SuppressWarnings("nls")
public final class TMarcadorInicio extends Token
{
    public TMarcadorInicio()
    {
        super.setText("Com sua licenca, por aqui vamos comecar!");
    }

    public TMarcadorInicio(int line, int pos)
    {
        super.setText("Com sua licenca, por aqui vamos comecar!");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TMarcadorInicio(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTMarcadorInicio(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TMarcadorInicio text.");
    }
}
