/* This file was generated by SableCC (http://www.sablecc.org/). */

package cordelmaisum.node;

import cordelmaisum.analysis.Analysis;

@SuppressWarnings("nls")
public final class TNada extends Token
{
    public TNada()
    {
        super.setText("nada");
    }

    public TNada(int line, int pos)
    {
        super.setText("nada");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TNada(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTNada(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TNada text.");
    }
}
