/* This file was generated by SableCC (http://www.sablecc.org/). */

package cordelmaisum.node;

import cordelmaisum.analysis.Analysis;

@SuppressWarnings("nls")
public final class TOValorDe extends Token
{
    public TOValorDe()
    {
        super.setText("o valor de");
    }

    public TOValorDe(int line, int pos)
    {
        super.setText("o valor de");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TOValorDe(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTOValorDe(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TOValorDe text.");
    }
}
