/* This file was generated by SableCC (http://www.sablecc.org/). */

package cordelmaisum.node;

import cordelmaisum.analysis.Analysis;

@SuppressWarnings("nls")
public final class TQueTem extends Token
{
    public TQueTem()
    {
        super.setText("que tem");
    }

    public TQueTem(int line, int pos)
    {
        super.setText("que tem");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TQueTem(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTQueTem(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TQueTem text.");
    }
}
