/* This file was generated by SableCC (http://www.sablecc.org/). */

package cordelmaisum.node;

import cordelmaisum.analysis.Analysis;

@SuppressWarnings("nls")
public final class TQueArruma extends Token
{
    public TQueArruma()
    {
        super.setText("que arruma");
    }

    public TQueArruma(int line, int pos)
    {
        super.setText("que arruma");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TQueArruma(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTQueArruma(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TQueArruma text.");
    }
}
