/* This file was generated by SableCC (http://www.sablecc.org/). */

package cordelmaisum.node;

import cordelmaisum.analysis.Analysis;

@SuppressWarnings("nls")
public final class TQue extends Token
{
    public TQue()
    {
        super.setText("que");
    }

    public TQue(int line, int pos)
    {
        super.setText("que");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TQue(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTQue(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TQue text.");
    }
}
