/* This file was generated by SableCC (http://www.sablecc.org/). */

package cordelmaisum.node;

import cordelmaisum.analysis.Analysis;

@SuppressWarnings("nls")
public final class TResultado extends Token
{
    public TResultado()
    {
        super.setText("resultado");
    }

    public TResultado(int line, int pos)
    {
        super.setText("resultado");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TResultado(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTResultado(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TResultado text.");
    }
}
