/* This file was generated by SableCC (http://www.sablecc.org/). */

package cordelmaisum.node;

import cordelmaisum.analysis.Analysis;

@SuppressWarnings("nls")
public final class TResposta extends Token
{
    public TResposta()
    {
        super.setText("resposta");
    }

    public TResposta(int line, int pos)
    {
        super.setText("resposta");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TResposta(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTResposta(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TResposta text.");
    }
}
