/* This file was generated by SableCC (http://www.sablecc.org/). */

package cordelmaisum.node;

import cordelmaisum.analysis.*;

@SuppressWarnings("nls")
public final class TSeCondicional extends Token
{
    public TSeCondicional()
    {
        super.setText("Se");
    }

    public TSeCondicional(int line, int pos)
    {
        super.setText("Se");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TSeCondicional(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTSeCondicional(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TSeCondicional text.");
    }
}
