/* This file was generated by SableCC (http://www.sablecc.org/). */

package cordelmaisum.node;

import cordelmaisum.analysis.Analysis;

@SuppressWarnings("nls")
public final class TSua extends Token
{
    public TSua()
    {
        super.setText("sua");
    }

    public TSua(int line, int pos)
    {
        super.setText("sua");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TSua(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTSua(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TSua text.");
    }
}
