/* This file was generated by SableCC (http://www.sablecc.org/). */

package cordelmaisum.node;

import cordelmaisum.analysis.*;

@SuppressWarnings("nls")
public final class TTem extends Token
{
    public TTem()
    {
        super.setText("tem");
    }

    public TTem(int line, int pos)
    {
        super.setText("tem");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TTem(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTTem(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TTem text.");
    }
}
