/* This file was generated by SableCC (http://www.sablecc.org/). */

package cordelmaisum.node;

import cordelmaisum.analysis.*;

@SuppressWarnings("nls")
public final class TUma extends Token
{
    public TUma()
    {
        super.setText("uma");
    }

    public TUma(int line, int pos)
    {
        super.setText("uma");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TUma(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTUma(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TUma text.");
    }
}
