/* This file was generated by SableCC (http://www.sablecc.org/). */

package cordelmaisum.node;

import cordelmaisum.analysis.*;

@SuppressWarnings("nls")
public final class TVamos extends Token
{
    public TVamos()
    {
        super.setText("vamos");
    }

    public TVamos(int line, int pos)
    {
        super.setText("vamos");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TVamos(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTVamos(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TVamos text.");
    }
}
