/* This file was generated by SableCC (http://www.sablecc.org/). */

package cordelmaisum.node;

import cordelmaisum.analysis.Analysis;

@SuppressWarnings("nls")
public final class TVoce extends Token
{
    public TVoce()
    {
        super.setText("voce");
    }

    public TVoce(int line, int pos)
    {
        super.setText("voce");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TVoce(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTVoce(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TVoce text.");
    }
}
