/* This file was generated by SableCC (http://www.sablecc.org/). */

package cordelmaisum.node;

import cordelmaisum.analysis.Analysis;

@SuppressWarnings("nls")
public final class TVoceArranjar extends Token
{
    public TVoceArranjar()
    {
        super.setText("voce arranjar");
    }

    public TVoceArranjar(int line, int pos)
    {
        super.setText("voce arranjar");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TVoceArranjar(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTVoceArranjar(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TVoceArranjar text.");
    }
}
